In [1]:
%pylab inline
from __future__ import division
import scipy as sp
from scipy import stats
from scipy.signal import argrelextrema
from scipy.interpolate import interp1d
import operator as op
from decimal import *
# import pickle
# from mpl_toolkits.mplot3d import Axes3D
import mpld3
mpld3.enable_notebook()

Populating the interactive namespace from numpy and matplotlib


In [2]:
%run ../cow.py
%run ../optimize_pkg_2.py

In [3]:
filepath_down = "../data_tables/polyanskiy_down/n"
filepath_up = "../data_tables/polyanskiy_up/n"
protocolbit = 4*10**4
protocol_target = 10**(-9)

## N = 15
[4.56, -5.94, -3.87]

In [19]:
%%time
N = 15
tSNR_range = [4.55]
rSNR3_range = np.arange(-3.9, -3.87+0.001, 0.01)
rSNRdu_range = np.arange(-6, -5.8+0.001, 0.02)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (4, 11) size of matrix 44
[[  1.04469011e-09   1.03773123e-09   1.03335640e-09   1.03139808e-09
    1.03171183e-09   1.03407605e-09   1.03837527e-09   1.04444597e-09
    1.05222209e-09   1.06160325e-09   1.07254872e-09]
 [  1.04022391e-09   1.03314812e-09   1.02869979e-09   1.02667796e-09
    1.02695552e-09   1.02932862e-09   1.03366071e-09   1.03980713e-09
    1.04766251e-09   1.05712417e-09   1.06821296e-09]
 [  1.03848419e-09   1.03127573e-09   1.02674724e-09   1.02464726e-09
    1.02492159e-09   1.02731745e-09   1.03169018e-09   1.03789000e-09
    1.04583942e-09   1.05541853e-09   1.06663045e-09]
 [  1.03917330e-09   1.03183073e-09   1.02720654e-09   1.02507081e-09
    1.02530995e-09   1.02773012e-09   1.03216169e-09   1.03842546e-09
    1.04647457e-09   1.05618603e-09   1.06754505e-09]]
CPU times: user 2min 49s, sys: 1.02 s, total: 2min 50s
Wall time: 2min 54s


In [20]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-5.94
-5.94
-5.94
-5.94


In [21]:
%%time
%run ../optimize_pkg_2.py
N = 15
tSNR_range = np.arange(4.5, 4.6+0.001, 0.01)
rSNR3_range = np.arange(-3.9, -3.87+0.001, 0.01)
rSNRdu_range = [-5.94]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 4) size of matrix 44
[[  1.17437260e-09   1.17190757e-09   1.17224175e-09   1.17508270e-09]
 [  1.14406684e-09   1.14112642e-09   1.14094145e-09   1.14327015e-09]
 [  1.11463228e-09   1.11122123e-09   1.11056164e-09   1.11238729e-09]
 [  1.08606757e-09   1.08219889e-09   1.08107556e-09   1.08240805e-09]
 [  1.05832532e-09   1.05401976e-09   1.05244791e-09   1.05330511e-09]
 [  1.03139786e-09   1.02667808e-09   1.02464726e-09   1.02507103e-09]
 [  1.00525077e-09   1.00011799e-09   9.97678162e-10   9.97654515e-10]
 [  9.79863080e-10   9.74329173e-10   9.71487779e-10   9.71031922e-10]
 [  9.55216128e-10   9.49296419e-10   9.46060119e-10   9.45216794e-10]
 [  9.31285049e-10   9.25002297e-10   9.21372312e-10   9.20124088e-10]
 [  9.08044528e-10   9.01406727e-10   8.97407371e-10   8.95788888e-10]]
CPU times: user 3min, sys: 1.47 s, total: 3min 1s
Wall time: 3min 7s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [22]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-3.89
-3.88
-3.88
-3.88
-3.88
-3.88
-3.87
-3.87
-3.87
-3.87
-3.87


## N = 16
[4.41, -5.65, -3.56]

In [27]:
%%time
N = 16
tSNR_range = [4.55]
rSNR3_range = np.arange(-3.7, -3.6+0.001, 0.1)
rSNRdu_range = np.arange(-5.8, -5.6+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 21) size of matrix 42
[[  1.15484933e-09   1.14824772e-09   1.14225895e-09   1.13693588e-09
    1.13217513e-09   1.12798304e-09   1.12430509e-09   1.12110021e-09
    1.11838583e-09   1.11610376e-09   1.11430398e-09   1.11285836e-09
    1.11181975e-09   1.11114495e-09   1.11083032e-09   1.11089471e-09
    1.11131104e-09   1.11197729e-09   1.11300513e-09   1.11430831e-09
    1.11586995e-09]
 [  7.57178320e-10   7.49658224e-10   7.42766182e-10   7.36586792e-10
    7.31024574e-10   7.26067206e-10   7.21681825e-10   7.17808812e-10
    7.14487025e-10   7.11588011e-10   7.09167169e-10   7.07173209e-10
    7.05617342e-10   7.04455050e-10   7.03661351e-10   7.03244019e-10
    7.03197500e-10   7.03527236e-10   7.04158398e-10   7.05117076e-10
    7.06363967e-10]]
CPU times: user 3min 30s, sys: 1.05 s, total: 3min 31s
Wall time: 3min 36s


In [28]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-5.66
-5.64


In [35]:
%%time
%run ../optimize_pkg_2.py
N = 16
tSNR_range = np.arange(4.4, 4.45+0.001, 0.01)
rSNR3_range = np.arange(-3.59, -3.55+0.001, 0.01)
rSNRdu_range = [-5.65]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (6, 5) size of matrix 30
[[  1.01765540e-09   1.01266107e-09   1.01050246e-09   1.01090158e-09
    1.01359809e-09]
 [  9.90734383e-10   9.85291182e-10   9.82683046e-10   9.82600112e-10
    9.84805792e-10]
 [  9.64647140e-10   9.58760071e-10   9.55708512e-10   9.55168500e-10
    9.56888235e-10]
 [  9.39349820e-10   9.33048860e-10   9.29559874e-10   9.28582100e-10
    9.29841315e-10]
 [  9.14835541e-10   9.08139897e-10   9.04213260e-10   9.02802166e-10
    9.03631614e-10]
 [  8.91068108e-10   8.83976004e-10   8.79657902e-10   8.77831141e-10
    8.78219164e-10]]
CPU times: user 2min 21s, sys: 706 ms, total: 2min 22s
Wall time: 2min 25s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [36]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-3.57
-3.56
-3.56
-3.56
-3.56
-3.56


## N = 17
[4.28, -5.38, -3.27]

In [49]:
%%time
N = 17
tSNR_range = [4.25]
rSNR3_range = np.arange(-3.4, -3.3+0.001, 0.1)
rSNRdu_range = np.arange(-5.5, -5.3+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 21) size of matrix 42
[[  1.45843948e-09   1.45094603e-09   1.44430568e-09   1.43856593e-09
    1.43358325e-09   1.42933876e-09   1.42584777e-09   1.42302314e-09
    1.42084877e-09   1.41930701e-09   1.41834733e-09   1.41796541e-09
    1.41815926e-09   1.41890666e-09   1.42013123e-09   1.42188783e-09
    1.42415102e-09   1.42684531e-09   1.42998646e-09   1.43355416e-09
    1.43760415e-09]
 [  1.14376786e-09   1.13483156e-09   1.12690235e-09   1.11990328e-09
    1.11382781e-09   1.10862297e-09   1.10418752e-09   1.10052911e-09
    1.09764597e-09   1.09543441e-09   1.09391551e-09   1.09304854e-09
    1.09280129e-09   1.09315490e-09   1.09412235e-09   1.09564158e-09
    1.09772036e-09   1.10032838e-09   1.10342779e-09   1.10701526e-09
    1.11110776e-09]]
CPU times: user 4min 13s, sys: 2.24 s, total: 4min 15s
Wall time: 4min 27s


In [50]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-5.39
-5.38


In [55]:
%%time
%run ../optimize_pkg_2.py
N = 17
tSNR_range = np.arange(4.2, 4.3+0.001, 0.01)
rSNR3_range = np.arange(-3.29, -3.26+0.001, 0.01)
rSNRdu_range = [-5.38]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 4) size of matrix 44
[[  1.25826938e-09   1.25994148e-09   1.26448552e-09   1.27163058e-09]
 [  1.22201727e-09   1.22302346e-09   1.22689336e-09   1.23334853e-09]
 [  1.18692967e-09   1.18729204e-09   1.19050858e-09   1.19629129e-09]
 [  1.15296650e-09   1.15271259e-09   1.15529153e-09   1.16042753e-09]
 [  1.12009224e-09   1.11925114e-09   1.12121856e-09   1.12571830e-09]
 [  1.08827258e-09   1.08686216e-09   1.08823328e-09   1.09212650e-09]
 [  1.05747999e-09   1.05551434e-09   1.05631370e-09   1.05961495e-09]
 [  1.02767561e-09   1.02517606e-09   1.02543074e-09   1.02816367e-09]
 [  9.98826577e-10   9.95817984e-10   9.95544536e-10   9.97718463e-10]
 [  9.70896918e-10   9.67397940e-10   9.66616232e-10   9.68274794e-10]
 [  9.43870648e-10   9.39883504e-10   9.38606970e-10   9.39758604e-10]]
CPU times: user 4min 7s, sys: 985 ms, total: 4min 8s
Wall time: 4min 12s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [56]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-3.29
-3.29
-3.29
-3.28
-3.28
-3.28
-3.28
-3.28
-3.27
-3.27
-3.27


In [ ]:
## N = 18

In [59]:
%%time
N = 18
tSNR_range = [4.2]
rSNR3_range = np.arange(-3.1, -3+0.001, 0.1)
rSNRdu_range = np.arange(-5.2, -5.+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 21) size of matrix 42
[[  1.17228793e-09   1.16861254e-09   1.16559895e-09   1.16315779e-09
    1.16126531e-09   1.15994347e-09   1.15915277e-09   1.15886312e-09
    1.15906851e-09   1.15974375e-09   1.16086230e-09   1.16244570e-09
    1.16445587e-09   1.16688115e-09   1.16970233e-09   1.17290444e-09
    1.17647514e-09   1.18040899e-09   1.18471166e-09   1.18937715e-09
    1.19438937e-09]
 [  9.53045642e-10   9.48448098e-10   9.44623157e-10   9.41492662e-10
    9.38965350e-10   9.37096734e-10   9.35830635e-10   9.35144406e-10
    9.35020505e-10   9.35436728e-10   9.36376088e-10   9.37822153e-10
    9.39778255e-10   9.42184109e-10   9.45077128e-10   9.48433110e-10
    9.52178114e-10   9.56388302e-10   9.60979962e-10   9.66002056e-10
    9.71406733e-10]]
CPU times: user 4min 29s, sys: 1.29 s, total: 4min 30s
Wall time: 4min 37s


In [60]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-5.13
-5.12


In [ ]:
%%time
%run ../optimize_pkg_2.py
N = 18
tSNR_range = np.arange(4, 4.3+0.001, 0.1)
rSNR3_range = np.arange(-3.1, -3+0.001, 0.1)
rSNRdu_range = [-5.12]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

In [ ]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)