In [1]:
%pylab inline
from __future__ import division
import scipy as sp
from scipy import stats
from scipy.signal import argrelextrema
from scipy.interpolate import interp1d
import operator as op
from decimal import *
# import pickle
# from mpl_toolkits.mplot3d import Axes3D
import mpld3
mpld3.enable_notebook()

Populating the interactive namespace from numpy and matplotlib


In [2]:
%run ../cow.py
%run ../optimize_pkg_2.py

In [6]:
filepath_down = "../data_tables/polyanskiy_down/n"
filepath_up = "../data_tables/polyanskiy_up/n"
protocolbit = 4*10**4
protocol_target = 10**(-9)

## N = 6
[10.15, -9.71, -8.21]

In [39]:
%%time
%run ../optimize_pkg_2.py
N = 6
tSNR_range = np.arange(10.14, 10.161, 0.01)
rSNR3_range = np.arange(-8.23, -8.2+0.01, 0.01)
rSNRdu_range = [-9.71]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (3, 5) size of matrix 15
[[  1.01107900e-09   1.00960618e-09   1.00918618e-09   1.00971354e-09
    1.01109288e-09]
 [  9.98466088e-10   9.96912219e-10   9.96408289e-10   9.96848604e-10
    9.98138683e-10]
 [  9.86019821e-10   9.84386128e-10   9.83799264e-10   9.84154203e-10
    9.85356130e-10]]
CPU times: user 5.79 s, sys: 79.7 ms, total: 5.87 s
Wall time: 6.16 s


In [40]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-8.21
-8.21
-8.21


In [37]:
%%time
N = 6
tSNR_range = [10.14]
rSNR3_range = np.arange(-8.23, -8.2+0.01, 0.01)
rSNRdu_range = np.arange(-9.74, -9.7, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (5, 5) size of matrix 25
[[  1.01224173e-09   1.01144781e-09   1.01120667e-09   1.01107900e-09
    1.01144859e-09]
 [  1.01076625e-09   1.00996989e-09   1.00973307e-09   1.00960618e-09
    1.00998121e-09]
 [  1.01034081e-09   1.00954312e-09   1.00931152e-09   1.00918618e-09
    1.00956787e-09]
 [  1.01064768e-09   1.01006159e-09   1.00961950e-09   1.00971354e-09
    1.01010267e-09]
 [  1.01201048e-09   1.01143072e-09   1.01099040e-09   1.01109288e-09
    1.01149034e-09]]
CPU times: user 10.2 s, sys: 126 ms, total: 10.4 s
Wall time: 11.3 s


In [38]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-9.71
-9.71
-9.71
-9.72
-9.72


## N = 7
[8.65, -9.11, -7.48]

In [61]:
%%time
N = 7
tSNR_range = [8.6]
rSNR3_range = np.arange(-7.49, -7.46+0.001, 0.01)
rSNRdu_range = np.arange(-9.2, -9.1+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (4, 11) size of matrix 44
[[  1.07807907e-09   1.07468445e-09   1.07121423e-09   1.06829534e-09
    1.06601927e-09   1.06409304e-09   1.06275166e-09   1.06181219e-09
    1.06126929e-09   1.06123976e-09   1.06132214e-09]
 [  1.07801035e-09   1.07448195e-09   1.07111819e-09   1.06818354e-09
    1.06589582e-09   1.06396025e-09   1.06261477e-09   1.06167342e-09
    1.06112874e-09   1.06110365e-09   1.06118858e-09]
 [  1.07905507e-09   1.07539111e-09   1.07213571e-09   1.06918585e-09
    1.06688680e-09   1.06494202e-09   1.06346554e-09   1.06265086e-09
    1.06210496e-09   1.06195930e-09   1.06217413e-09]
 [  1.08110088e-09   1.07742126e-09   1.07403131e-09   1.07118936e-09
    1.06875331e-09   1.06692610e-09   1.06544429e-09   1.06463183e-09
    1.06408549e-09   1.06394471e-09   1.06416598e-09]]
CPU times: user 23.3 s, sys: 113 ms, total: 23.5 s
Wall time: 23.9 s


In [62]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-9.11
-9.11
-9.11
-9.11


In [63]:
%%time
%run ../optimize_pkg_2.py
N = 7
tSNR_range = np.arange(8.6, 8.7, 0.01)
rSNR3_range = np.arange(-7.49, -7.46+0.001, 0.01)
rSNRdu_range = [-9.11]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (10, 4) size of matrix 40
[[  1.06123976e-09   1.06110365e-09   1.06195930e-09   1.06394471e-09]
 [  1.04593056e-09   1.04567521e-09   1.04653419e-09   1.04826825e-09]
 [  1.03085518e-09   1.03048214e-09   1.03122022e-09   1.03295694e-09]
 [  1.01600950e-09   1.01552122e-09   1.01614062e-09   1.01775521e-09]
 [  1.00139019e-09   1.00078867e-09   1.00129127e-09   1.00278608e-09]
 [  9.86994042e-10   9.86281279e-10   9.86669191e-10   9.88045978e-10]
 [  9.72817271e-10   9.71995373e-10   9.72270375e-10   9.73531256e-10]
 [  9.58856661e-10   9.57927293e-10   9.58091828e-10   9.59238688e-10]
 [  9.45108991e-10   9.44074041e-10   9.44129774e-10   9.45164946e-10]
 [  9.31570598e-10   9.30432398e-10   9.30381105e-10   9.31306143e-10]]
CPU times: user 22.3 s, sys: 274 ms, total: 22.6 s
Wall time: 24 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [64]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-7.48
-7.48
-7.48
-7.48
-7.48
-7.48
-7.48
-7.48
-7.48
-7.47


## N = 8
[7.56, -8.58, -6.85]

In [84]:
%%time
N = 8
tSNR_range = [7.55]
rSNR3_range = np.arange(-6.81, -6.79+0.001, 0.01)
rSNRdu_range = np.arange(-8.62, -8.58+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (3, 5) size of matrix 15
[[  1.02509201e-09   1.02347164e-09   1.02222764e-09   1.02136122e-09
    1.02084841e-09]
 [  1.02963327e-09   1.02800901e-09   1.02676245e-09   1.02589393e-09
    1.02538156e-09]
 [  1.03492015e-09   1.03313424e-09   1.03204356e-09   1.03109432e-09
    1.03066256e-09]]
CPU times: user 11.2 s, sys: 72.6 ms, total: 11.3 s
Wall time: 11.5 s


In [85]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-8.58
-8.58
-8.58


In [87]:
%%time
%run ../optimize_pkg_2.py
N = 8
tSNR_range = np.arange(7.5, 7.561, 0.01)
rSNR3_range = np.arange(-6.87, -6.8+0.001, 0.01)
rSNRdu_range = [-8.58]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (7, 8) size of matrix 56
[[  1.09986331e-09   1.09855236e-09   1.09867537e-09   1.10008691e-09
    1.10265597e-09   1.10626708e-09   1.11081611e-09   1.11621146e-09]
 [  1.08222831e-09   1.08076281e-09   1.08072706e-09   1.08197484e-09
    1.08437614e-09   1.08781539e-09   1.09218945e-09   1.09740572e-09]
 [  1.06496889e-09   1.06327958e-09   1.06308762e-09   1.06417519e-09
    1.06641207e-09   1.06968290e-09   1.07388454e-09   1.07892562e-09]
 [  1.04793396e-09   1.04609721e-09   1.04575260e-09   1.04668263e-09
    1.04875819e-09   1.05186382e-09   1.05589659e-09   1.06076481e-09]
 [  1.03119169e-09   1.02928333e-09   1.02871600e-09   1.02949216e-09
    1.03140918e-09   1.03435249e-09   1.03821962e-09   1.04291886e-09]
 [  1.01473718e-09   1.01268638e-09   1.01197317e-09   1.01259801e-09
    1.01435960e-09   1.01714392e-09   1.02084841e-09   1.02538156e-09]
 [  9.98565342e-10   9.96375205e-10   9.95591165e-10   9.95995286e-10
    9.97604888e-10   1.00023301e-09   1.00377773e-09

<string>:182: RuntimeWarning: divide by zero encountered in log10


In [88]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-6.86
-6.85
-6.85
-6.85
-6.85
-6.85
-6.85


## N = 9
[6.76, -8.09, -6.29]

In [104]:
%%time
%run ../optimize_pkg_2.py
N = 9
tSNR_range = np.arange(6.75, 6.76+0.001, 0.01)
rSNR3_range = np.arange(-6.3, -6.27+0.001, 0.01)
rSNRdu_range = [-8.09]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (2, 4) size of matrix 8
[[  1.00450959e-09   1.00441722e-09   1.00562370e-09   1.00809006e-09]
 [  9.86577153e-10   9.86304816e-10   9.87376625e-10   9.89604620e-10]]
CPU times: user 8.4 s, sys: 91.5 ms, total: 8.5 s
Wall time: 9 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [105]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-6.29
-6.29


In [96]:
%%time
N = 9
tSNR_range = [6.9]
rSNR3_range = np.arange(-6.3, -6.3+0.001, 0.1)
rSNRdu_range = np.arange(-8.2, -8.0+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (1, 21) size of matrix 21
[[  7.91556709e-10   7.87220400e-10   7.83548781e-10   7.80345455e-10
    7.77722331e-10   7.75310927e-10   7.73245690e-10   7.71686715e-10
    7.70363551e-10   7.69516006e-10   7.69045494e-10   7.68958563e-10
    7.69123987e-10   7.69584063e-10   7.70314146e-10   7.71313902e-10
    7.72663933e-10   7.74016184e-10   7.75811193e-10   7.77816256e-10
    7.79990073e-10]]
CPU times: user 20.5 s, sys: 180 ms, total: 20.7 s
Wall time: 21.4 s


In [97]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-8.09


## N = 10
[6.14, -7.66, -5.8]

In [122]:
%%time
%run ../optimize_pkg_2.py
N = 10
tSNR_range = np.arange(6.1, 6.2+0.001, 0.01)
rSNR3_range = np.arange(-5.81, -5.79+0.001, 0.01)
rSNRdu_range = [-7.66]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 3) size of matrix 33
[[  1.08089759e-09   1.08053622e-09   1.08176956e-09]
 [  1.05994680e-09   1.05935427e-09   1.06038378e-09]
 [  1.03943476e-09   1.03861608e-09   1.03941344e-09]
 [  1.01935260e-09   1.01831288e-09   1.01888342e-09]
 [  9.99690553e-10   9.98435667e-10   9.98784389e-10]
 [  9.80440618e-10   9.78975345e-10   9.79107462e-10]
 [  9.61593805e-10   9.59922364e-10   9.59843094e-10]
 [  9.43141565e-10   9.41269285e-10   9.40983291e-10]
 [  9.25075350e-10   9.23007448e-10   9.22519616e-10]
 [  9.07387498e-10   9.05128306e-10   9.04443187e-10]
 [  8.90069463e-10   8.87623752e-10   8.86746010e-10]]
CPU times: user 44.7 s, sys: 366 ms, total: 45 s
Wall time: 47 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [123]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-5.8
-5.8
-5.8
-5.8
-5.8
-5.8
-5.79
-5.79
-5.79
-5.79
-5.79


In [120]:
%%time
N = 10
tSNR_range = [6.1]
rSNR3_range = np.arange(-5.82, -5.78+0.001, 0.01)
rSNRdu_range = np.arange(-7.7, -7.5+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (5, 21) size of matrix 105
[[  1.08650777e-09   1.08486553e-09   1.08373732e-09   1.08327125e-09
    1.08307496e-09   1.08332665e-09   1.08415221e-09   1.08530174e-09
    1.08698672e-09   1.08891829e-09   1.09126652e-09   1.09405018e-09
    1.09712706e-09   1.10051224e-09   1.10421738e-09   1.10833220e-09
    1.11269538e-09   1.11735154e-09   1.12215515e-09   1.12725629e-09
    1.13269327e-09]
 [  1.08437315e-09   1.08268039e-09   1.08157117e-09   1.08106568e-09
    1.08089759e-09   1.08114673e-09   1.08197729e-09   1.08313358e-09
    1.08483111e-09   1.08677600e-09   1.08914122e-09   1.09194631e-09
    1.09498854e-09   1.09846199e-09   1.10219667e-09   1.10631404e-09
    1.11071474e-09   1.11544751e-09   1.12029142e-09   1.12543630e-09
    1.13088661e-09]
 [  1.08404929e-09   1.08233844e-09   1.08118892e-09   1.08067244e-09
    1.08053622e-09   1.08078502e-09   1.08158849e-09   1.08275344e-09
    1.08443232e-09   1.08645970e-09   1.08884390e-09   1.09167408e-09
    1.09471443e-

In [121]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-7.66
-7.66
-7.66
-7.66
-7.66


## N = 11
[5.67, -7.26, -5.35]

In [132]:
%%time
N = 11
tSNR_range = [5.65]
rSNR3_range = np.arange(-5.5, -5.3+0.001, 0.1)
rSNRdu_range = np.arange(-7.3, -7.1+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (3, 21) size of matrix 63
[[  1.40807843e-09   1.40695933e-09   1.40638212e-09   1.40619272e-09
    1.40646794e-09   1.40710388e-09   1.40814094e-09   1.40975365e-09
    1.41169076e-09   1.41395773e-09   1.41666945e-09   1.41953249e-09
    1.42282808e-09   1.42637324e-09   1.43027012e-09   1.43439416e-09
    1.43887391e-09   1.44364698e-09   1.44857415e-09   1.45385504e-09
    1.45934254e-09]
 [  1.05872622e-09   1.05716891e-09   1.05620768e-09   1.05570719e-09
    1.05561893e-09   1.05603370e-09   1.05682529e-09   1.05803888e-09
    1.05963638e-09   1.06166054e-09   1.06411935e-09   1.06692666e-09
    1.07001330e-09   1.07333786e-09   1.07701004e-09   1.08102416e-09
    1.08535625e-09   1.09004150e-09   1.09487042e-09   1.10000897e-09
    1.10541953e-09]
 [  1.05030118e-09   1.04865028e-09   1.04737918e-09   1.04679287e-09
    1.04667808e-09   1.04704667e-09   1.04789977e-09   1.04922937e-09
    1.05107389e-09   1.05319775e-09   1.05576614e-09   1.05885811e-09
    1.06221643e-0

In [133]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-7.27
-7.26
-7.26


In [138]:
%%time
%run ../optimize_pkg_2.py
N = 11
tSNR_range = np.arange(5.66, 5.67+0.001, 0.01)
rSNR3_range = np.arange(-5.37, -5.33+0.001, 0.01)
rSNRdu_range = [-7.26]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (2, 5) size of matrix 10
[[  1.01131747e-09   1.00810282e-09   1.00682440e-09   1.00734465e-09
    1.00939745e-09]
 [  9.90637350e-10   9.87180004e-10   9.85669546e-10   9.85913351e-10
    9.87723014e-10]]
CPU times: user 16.8 s, sys: 106 ms, total: 16.9 s
Wall time: 17.4 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [139]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-5.35
-5.35


## N = 12
[5.29, -6.9, -4.94]

In [151]:
%%time
N = 12
tSNR_range = [5.2]
rSNR3_range = np.arange(-4.96, -4.93+0.001, 0.01)
rSNRdu_range = np.arange(-7, -6.89+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (4, 12) size of matrix 48
[[  1.25972710e-09   1.25258426e-09   1.24637989e-09   1.24107014e-09
    1.23658295e-09   1.23279364e-09   1.22977006e-09   1.22752120e-09
    1.22581079e-09   1.22475530e-09   1.22438348e-09   1.22459509e-09]
 [  1.25912303e-09   1.25190924e-09   1.24562893e-09   1.24023725e-09
    1.23570998e-09   1.23185884e-09   1.22880794e-09   1.22652888e-09
    1.22479205e-09   1.22370070e-09   1.22333543e-09   1.22354127e-09]
 [  1.26077726e-09   1.25345956e-09   1.24711852e-09   1.24162780e-09
    1.23704391e-09   1.23316113e-09   1.23007005e-09   1.22775146e-09
    1.22601684e-09   1.22487542e-09   1.22451782e-09   1.22468868e-09]
 [  1.26439725e-09   1.25703914e-09   1.25058974e-09   1.24504762e-09
    1.24040911e-09   1.23649313e-09   1.23331745e-09   1.23099897e-09
    1.22925825e-09   1.22809907e-09   1.22765276e-09   1.22790389e-09]]
CPU times: user 1min 45s, sys: 392 ms, total: 1min 45s
Wall time: 1min 47s


In [152]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-6.9
-6.9
-6.9
-6.9


In [153]:
%%time
%run ../optimize_pkg_2.py
N = 12
tSNR_range = np.arange(5.2, 5.3+0.001, 0.01)
rSNR3_range = np.arange(-4.96, -4.93+0.001, 0.01)
rSNRdu_range = [-6.9]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 4) size of matrix 44
[[  1.22438348e-09   1.22333543e-09   1.22451782e-09   1.22765276e-09]
 [  1.19724519e-09   1.19582610e-09   1.19664412e-09   1.19943788e-09]
 [  1.17073617e-09   1.16897281e-09   1.16945187e-09   1.17191457e-09]
 [  1.14487453e-09   1.14279175e-09   1.14290755e-09   1.14503074e-09]
 [  1.11965859e-09   1.11723275e-09   1.11701248e-09   1.11878951e-09]
 [  1.09504172e-09   1.09231246e-09   1.09176679e-09   1.09319109e-09]
 [  1.07103237e-09   1.06799569e-09   1.06713727e-09   1.06821818e-09]
 [  1.04761644e-09   1.04426245e-09   1.04310205e-09   1.04389675e-09]
 [  1.02475539e-09   1.02110831e-09   1.01964615e-09   1.02012965e-09]
 [  1.00244968e-09   9.98534810e-10   9.96763672e-10   9.96944083e-10]
 [  9.80704407e-10   9.76495662e-10   9.74438419e-10   9.74325953e-10]]
CPU times: user 1min 31s, sys: 358 ms, total: 1min 31s
Wall time: 1min 33s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [154]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-4.95
-4.95
-4.95
-4.95
-4.94
-4.94
-4.94
-4.94
-4.94
-4.94
-4.93


## N = 13
[5, -6.55, -4.56]

In [159]:
%%time
N = 13
tSNR_range = [5]
rSNR3_range = np.arange(-4.6, -4.5+0.001, 0.1)
rSNRdu_range = np.arange(-6.7, -6.5+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 21) size of matrix 42
[[  1.06476317e-09   1.05534281e-09   1.04678721e-09   1.03901310e-09
    1.03216935e-09   1.02610942e-09   1.02070408e-09   1.01609432e-09
    1.01209752e-09   1.00872488e-09   1.00601882e-09   1.00384168e-09
    1.00219366e-09   1.00110220e-09   1.00046904e-09   1.00039044e-09
    1.00081132e-09   1.00163211e-09   1.00284470e-09   1.00452857e-09
    1.00665132e-09]
 [  1.07538167e-09   1.06458375e-09   1.05486730e-09   1.04609399e-09
    1.03829390e-09   1.03132702e-09   1.02521902e-09   1.01989139e-09
    1.01530662e-09   1.01142239e-09   1.00826225e-09   1.00574016e-09
    1.00384390e-09   1.00253916e-09   1.00183029e-09   1.00164210e-09
    1.00197362e-09   1.00286934e-09   1.00425079e-09   1.00602393e-09
    1.00831477e-09]]
CPU times: user 1min 55s, sys: 407 ms, total: 1min 56s
Wall time: 1min 58s


In [160]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-6.55
-6.55


In [169]:
%%time
%run ../optimize_pkg_2.py
N = 13
tSNR_range = np.arange(4.99, 5+0.001, 0.01)
rSNR3_range = np.arange(-4.57, -4.55+0.001, 0.01)
rSNRdu_range = [-6.55]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 3) size of matrix 33
[[  1.24462951e-09   1.24632149e-09   1.25020649e-09]
 [  1.21481802e-09   1.21608368e-09   1.21953025e-09]
 [  1.18578325e-09   1.18664645e-09   1.18966281e-09]
 [  1.15750520e-09   1.15797849e-09   1.16056786e-09]
 [  1.12998755e-09   1.13004561e-09   1.13223431e-09]
 [  1.10317633e-09   1.10284248e-09   1.10465193e-09]
 [  1.07706333e-09   1.07634968e-09   1.07779108e-09]
 [  1.05161990e-09   1.05058207e-09   1.05161990e-09]
 [  1.02684028e-09   1.02546449e-09   1.02613229e-09]
 [  1.00271658e-09   1.00099051e-09   1.00132191e-09]
 [  9.79220149e-10   9.77155468e-10   9.77172343e-10]]
CPU times: user 1min 29s, sys: 701 ms, total: 1min 30s
Wall time: 1min 33s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [170]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-4.57
-4.57
-4.57
-4.57
-4.57
-4.56
-4.56
-4.56
-4.56
-4.56
-4.56


## N = 14
[4.76, -6.23, -4.2]

In [187]:
%%time
N = 14
tSNR_range = [4.75]
rSNR3_range = np.arange(-4.21, -4.19+0.001, 0.01)
rSNRdu_range = np.arange(-6.3, -6.1+0.001, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (3, 21) size of matrix 63
[[  1.01705422e-09   1.01329567e-09   1.01019015e-09   1.00777098e-09
    1.00596509e-09   1.00476460e-09   1.00413733e-09   1.00397024e-09
    1.00435715e-09   1.00520747e-09   1.00659747e-09   1.00846920e-09
    1.01075925e-09   1.01349340e-09   1.01666731e-09   1.02022357e-09
    1.02415632e-09   1.02851483e-09   1.03324282e-09   1.03826525e-09
    1.04369247e-09]
 [  1.01719988e-09   1.01336195e-09   1.01021591e-09   1.00775599e-09
    1.00591713e-09   1.00468789e-09   1.00405939e-09   1.00385666e-09
    1.00425757e-09   1.00512876e-09   1.00651465e-09   1.00839170e-09
    1.01072395e-09   1.01347686e-09   1.01666575e-09   1.02030207e-09
    1.02427755e-09   1.02867093e-09   1.03343778e-09   1.03855480e-09
    1.04403985e-09]
 [  1.01938291e-09   1.01548137e-09   1.01230124e-09   1.00981079e-09
    1.00793263e-09   1.00667830e-09   1.00603648e-09   1.00582365e-09
    1.00621622e-09   1.00711073e-09   1.00850972e-09   1.01039788e-09
    1.01275732e-0

In [188]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-6.23
-6.23
-6.23


In [185]:
%%time
%run ../optimize_pkg_2.py
N = 14
tSNR_range = np.arange(4.75, 4.76+0.001, 0.01)
rSNR3_range = np.arange(-4.21, -4.19+0.001, 0.01)
rSNRdu_range = [-6.22]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 5) size of matrix 55
[[  1.14164667e-09   1.14128640e-09   1.14328813e-09   1.14739063e-09
    1.15342313e-09]
 [  1.11313070e-09   1.11232934e-09   1.11388720e-09   1.11754117e-09
    1.12310095e-09]
 [  1.08542020e-09   1.08418430e-09   1.08530984e-09   1.08852061e-09
    1.09362230e-09]
 [  1.05845188e-09   1.05684406e-09   1.05753417e-09   1.06032405e-09
    1.06496800e-09]
 [  1.03223052e-09   1.03022746e-09   1.03051268e-09   1.03289421e-09
    1.03710962e-09]
 [  1.00673403e-09   1.00435715e-09   1.00425757e-09   1.00621622e-09
    1.01003272e-09]
 [  9.81943415e-10   9.79195613e-10   9.78721770e-10   9.80279302e-10
    9.83701565e-10]
 [  9.57837698e-10   9.54731405e-10   9.53886969e-10   9.55079127e-10
    9.58092716e-10]
 [  9.34421207e-10   9.30960642e-10   9.29739730e-10   9.30562738e-10
    9.33203959e-10]
 [  9.11642650e-10   9.07836695e-10   9.06288378e-10   9.06734798e-10
    9.09007647e-10]
 [  8.89490703e-10   8.85360230e-10   8.83462303e-10   8.83577433e-

<string>:182: RuntimeWarning: divide by zero encountered in log10


In [186]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-4.21
-4.21
-4.21
-4.21
-4.21
-4.2
-4.2
-4.2
-4.2
-4.2
-4.2
