In [2]:
%pylab inline
from __future__ import division
import scipy as sp
from scipy import stats
from scipy.signal import argrelextrema
from scipy.interpolate import interp1d
import operator as op
from decimal import *
# import pickle
# from mpl_toolkits.mplot3d import Axes3D
import mpld3
mpld3.enable_notebook()

Populating the interactive namespace from numpy and matplotlib


In [3]:
%run ../cow.py
%run ../optimize_pkg_2.py

In [4]:
filepath_down = "../data_tables/hs_rs_downlink/n"
filepath_up = "../data_tables/hs_rs_uplink/n"
protocolbit = 4*10**4
protocol_target = 10**(-9)

In [5]:
optimize_3_data = zeros((len(range(2, 36)), 6))
start_node = 2

## N = 2

In [6]:
%%time
%run ../optimize_pkg_2.py
N = 2
tSNR_range = [47.09] # 47.09
rSNR3_range = np.arange(-0.4, -0.3, 0.01)
rSNRdu_range = np.arange(-0.4, -0.3, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (11, 11) size of matrix 121
[[  1.03523068e-09   1.03383035e-09   1.03365605e-09   1.03820075e-09
    1.03841735e-09   1.03977527e-09   1.04196851e-09   1.04478048e-09
    1.05211584e-09   1.05485798e-09   1.05805809e-09]
 [  1.02699371e-09   1.02256126e-09   1.02239994e-09   1.02694975e-09
    1.02716524e-09   1.02851694e-09   1.03069986e-09   1.03349829e-09
    1.04081743e-09   1.04354125e-09   1.04672127e-09]
 [  1.02101905e-09   1.01658282e-09   1.01338893e-09   1.01794284e-09
    1.01815734e-09   1.01950415e-09   1.02167874e-09   1.02446629e-09
    1.03177245e-09   1.03448150e-09   1.03764553e-09]
 [  1.01687414e-09   1.01243003e-09   1.00922726e-09   1.01074837e-09
    1.01096220e-09   1.01230491e-09   1.01447295e-09   1.01725184e-09
    1.02454756e-09   1.02724496e-09   1.03039610e-09]
 [  1.01420550e-09   1.00975073e-09   1.00653741e-09   1.00804820e-09
    1.00522779e-09   1.00656727e-09   1.00873010e-09   1.01150199e-09
    1.01878950e-09   1.02147757e-09   1.02461850e

In [7]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-0.38
-0.38
-0.38
-0.38
-0.36
-0.35
-0.34
-0.33
-0.33
-0.33
-0.33


In [8]:
%%time
%run ../optimize_pkg_2.py
N = 2
tSNR_range = np.arange(47, 47.1, 0.01)
rSNR3_range = np.arange(-0.4, -0.3, 0.01)
rSNRdu_range = [-0.33]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 11) size of matrix 121
[[  1.08768128e-09   1.07616382e-09   1.06694342e-09   1.05957854e-09
    1.05370879e-09   1.04904119e-09   1.04533793e-09   1.04240616e-09
    1.04327014e-09   1.04463560e-09   1.04640219e-09]
 [  1.08282761e-09   1.07133646e-09   1.06213727e-09   1.05478914e-09
    1.04893294e-09   1.04427600e-09   1.04058118e-09   1.03765629e-09
    1.03851083e-09   1.03986597e-09   1.04162112e-09]
 [  1.07799580e-09   1.06653097e-09   1.05735276e-09   1.05002151e-09
    1.04417874e-09   1.03953246e-09   1.03584608e-09   1.03292785e-09
    1.03377329e-09   1.03511799e-09   1.03686193e-09]
 [  1.07318598e-09   1.06174736e-09   1.05259024e-09   1.04527575e-09
    1.03944631e-09   1.03481079e-09   1.03113285e-09   1.02822129e-09
    1.02905751e-09   1.03039199e-09   1.03212461e-09]
 [  1.06839781e-09   1.05698550e-09   1.04784936e-09   1.04055164e-09
    1.03473552e-09   1.03011055e-09   1.02644104e-09   1.02353614e-09
    1.02436337e-09   1.02568765e-09   1.02740905e

In [9]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-0.33
-0.33
-0.33
-0.33
-0.33
-0.33
-0.33
-0.33
-0.33
-0.33
-0.33


## N = 3

In [10]:
%%time
N = 3
tSNR_range = [33.44]
rSNR3_range = np.arange(0.21, 0.31, 0.01) # 0.12
rSNRdu_range = np.arange(-0.25, -0.15, 0.01) # -0.18

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (10, 10) size of matrix 100
[[  1.02132791e-09   1.01619657e-09   1.01531361e-09   1.01183906e-09
    1.00926612e-09   1.00744835e-09   1.00626529e-09   1.00561781e-09
    1.00542374e-09   1.00561215e-09]
 [  1.02482811e-09   1.01969289e-09   1.01888142e-09   1.01539654e-09
    1.01281661e-09   1.01099462e-09   1.00980979e-09   1.00916298e-09
    1.00897091e-09   1.00916331e-09]
 [  1.02856934e-09   1.02343023e-09   1.02269049e-09   1.01919506e-09
    1.01660791e-09   1.01478204e-09   1.01359576e-09   1.01294939e-09
    1.01275999e-09   1.01295650e-09]
 [  1.03250763e-09   1.02736408e-09   1.02669617e-09   1.02319020e-09
    1.02059605e-09   1.01876607e-09   1.01757847e-09   1.01693298e-09
    1.01674635e-09   1.01694719e-09]
 [  1.03660713e-09   1.03145892e-09   1.03086284e-09   1.02734621e-09
    1.02474507e-09   1.02291109e-09   1.02172226e-09   1.02107789e-09
    1.02089404e-09   1.02109965e-09]
 [  1.04083875e-09   1.03568598e-09   1.03516173e-09   1.03163433e-09
    1.0290

In [11]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

-0.17
-0.17
-0.17
-0.17
-0.17
-0.17
-0.17
-0.17
-0.17
-0.17


In [12]:
%%time
%run ../optimize_pkg_2.py
N = 3
tSNR_range = np.arange(33.4, 33.5, 0.01)
rSNR3_range = np.arange(0.1, 0.2, 0.01)
rSNRdu_range = [-0.17]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 10) size of matrix 110
[[  1.03953057e-09   1.03186681e-09   1.02654285e-09   1.02313125e-09
    1.02128028e-09   1.02070186e-09   1.02115982e-09   1.02246123e-09
    1.02444853e-09   1.02699360e-09]
 [  1.03269504e-09   1.02502795e-09   1.01969522e-09   1.01627029e-09
    1.01440245e-09   1.01380404e-09   1.01423947e-09   1.01551656e-09
    1.01747788e-09   1.01999553e-09]
 [  1.02590580e-09   1.01823538e-09   1.01289399e-09   1.00945596e-09
    1.00757136e-09   1.00695319e-09   1.00736652e-09   1.00861941e-09
    1.01055486e-09   1.01304543e-09]
 [  1.01916264e-09   1.01148911e-09   1.00613917e-09   1.00268815e-09
    1.00078690e-09   1.00014930e-09   1.00054065e-09   1.00176945e-09
    1.00367947e-09   1.00614284e-09]
 [  1.01246500e-09   1.00478847e-09   9.99430205e-10   9.95966420e-10
    9.94048732e-10   9.93391702e-10   9.93761406e-10   9.94966332e-10
    9.96850935e-10   9.99287653e-10]
 [  1.00581243e-09   9.98133243e-10   9.92766758e-10   9.89290316e-10
    9.8735

In [13]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.15
0.15
0.15
0.15
0.15
0.15
0.15
0.15
0.15
0.15
0.15


## N = 4

In [267]:
%%time
%run ../optimize_pkg_2.py
N = 4
tSNR_range = [26.7] # 26.7
rSNR3_range = np.arange(0.53, 0.591, 0.01) # 0.5
rSNRdu_range = np.arange(-0.01, 0.011, 0.01) # 0.0

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (7, 3) size of matrix 21
[[  9.34435196e-10   9.34131328e-10   9.34203492e-10]
 [  9.28303878e-10   9.27994459e-10   9.28061628e-10]
 [  9.24257781e-10   9.23945476e-10   9.24010202e-10]
 [  9.21939969e-10   9.21626553e-10   9.21691501e-10]
 [  9.21053456e-10   9.20741150e-10   9.20808096e-10]
 [  9.21352106e-10   9.21042131e-10   9.21112853e-10]
 [  9.22631527e-10   9.22324994e-10   9.22400822e-10]]
CPU times: user 2.42 s, sys: 32.2 ms, total: 2.45 s
Wall time: 2.53 s


In [268]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [14]:
%%time
%run ../optimize_pkg_2.py
N = 4
tSNR_range = np.arange(26.55, 26.65, 0.01)
rSNR3_range = np.arange(0.56, 0.581, 0.01)
rSNRdu_range = [0.0]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (10, 3) size of matrix 30
[[  1.05313491e-09   1.05283804e-09   1.05377218e-09]
 [  1.04379949e-09   1.04345999e-09   1.04434839e-09]
 [  1.03454834e-09   1.03416675e-09   1.03501019e-09]
 [  1.02538067e-09   1.02495767e-09   1.02575648e-09]
 [  1.01629605e-09   1.01583197e-09   1.01658670e-09]
 [  1.00729369e-09   1.00678910e-09   1.00750019e-09]
 [  9.98372607e-10   9.97827820e-10   9.98495842e-10]
 [  9.89532234e-10   9.88947702e-10   9.89573201e-10]
 [  9.80771797e-10   9.80148074e-10   9.80731385e-10]
 [  9.72090630e-10   9.71428160e-10   9.71969727e-10]]
CPU times: user 3.84 s, sys: 85.7 ms, total: 3.92 s
Wall time: 4.24 s


In [15]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.57
0.57
0.57
0.57
0.57
0.57
0.57
0.57
0.57
0.57


## N = 5

In [255]:
%%time
%run ../optimize_pkg_2.py
N = 5
tSNR_range = [22.51] # 22.51
rSNR3_range = np.arange(0.91, 0.941, 0.01) # 0.90 --> 0.93
rSNRdu_range = np.arange(0.1, 0.18, 0.01) # 0.11 --> 0.14

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (4, 8) size of matrix 32
[[  9.98223504e-10   9.96737248e-10   9.95684646e-10   9.94804905e-10
    9.94423321e-10   9.94808014e-10   9.95886817e-10   9.96931093e-10]
 [  9.96295824e-10   9.94805016e-10   9.93760407e-10   9.92880222e-10
    9.92500748e-10   9.92898652e-10   9.93991334e-10   9.94653915e-10]
 [  9.95515115e-10   9.94428095e-10   9.93392590e-10   9.92513738e-10
    9.92137927e-10   9.92551485e-10   9.93660154e-10   9.94329619e-10]
 [  9.96437266e-10   9.95358462e-10   9.94333504e-10   9.93457316e-10
    9.93086613e-10   9.93517490e-10   9.94643923e-10   9.95322269e-10]]
CPU times: user 6.52 s, sys: 77.9 ms, total: 6.6 s
Wall time: 7.39 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [256]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.14
0.14
0.14
0.14


In [16]:
%%time
%run ../optimize_pkg_2.py
N = 5
tSNR_range = np.arange(22.45, 22.55, 0.01)
rSNR3_range = np.arange(0.91, 0.951, 0.01)
rSNRdu_range = [0.14]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 5) size of matrix 55
[[  1.06155984e-09   1.06001441e-09   1.06005260e-09   1.06142262e-09
    1.06391274e-09]
 [  1.05005304e-09   1.04844233e-09   1.04841147e-09   1.04970899e-09
    1.05212361e-09]
 [  1.03867503e-09   1.03700015e-09   1.03690123e-09   1.03812703e-09
    1.04046716e-09]
 [  1.02742459e-09   1.02568642e-09   1.02552000e-09   1.02667530e-09
    1.02894182e-09]
 [  1.01630016e-09   1.01449960e-09   1.01426689e-09   1.01535236e-09
    1.01754605e-09]
 [  1.00530007e-09   1.00343811e-09   1.00314002e-09   1.00415654e-09
    1.00627873e-09]
 [  9.94423321e-10   9.92500748e-10   9.92137927e-10   9.93086613e-10
    9.95137861e-10]
 [  9.83668258e-10   9.81685955e-10   9.81259518e-10   9.82141146e-10
    9.84122561e-10]
 [  9.73033654e-10   9.70992398e-10   9.70503233e-10   9.71318692e-10
    9.73230940e-10]
 [  9.62518176e-10   9.60418745e-10   9.59867741e-10   9.60617919e-10
    9.62462110e-10]
 [  9.52120160e-10   9.49963552e-10   9.49351486e-10   9.50037271e-

<string>:182: RuntimeWarning: divide by zero encountered in log10


In [17]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.92
0.93
0.93
0.93
0.93
0.93
0.93
0.93
0.93
0.93
0.93


## N = 6

In [246]:
%%time
%run ../optimize_pkg_2.py
N = 6
tSNR_range = [19.8] # 19.78
rSNR3_range = np.arange(1.2, 1.31, 0.01) # 1.24
rSNRdu_range = np.arange(0.25, 0.35, 0.01) # 0.3

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (12, 10) size of matrix 120
[[  1.00699538e-09   1.00586428e-09   1.00503261e-09   1.00490283e-09
    1.00499620e-09   1.00588049e-09   1.00690334e-09   1.00862807e-09
    1.01004494e-09   1.01196962e-09]
 [  9.94789362e-10   9.93645388e-10   9.92803284e-10   9.92671501e-10
    9.92755878e-10   9.93637173e-10   9.94657801e-10   9.96390970e-10
    9.97801619e-10   9.99506700e-10]
 [  9.85715065e-10   9.84561099e-10   9.83711224e-10   9.83581105e-10
    9.83660486e-10   9.84542559e-10   9.85565740e-10   9.87312454e-10
    9.88721549e-10   9.90427074e-10]
 [  9.79308190e-10   9.78146342e-10   9.77291359e-10   9.77166015e-10
    9.77243064e-10   9.78130021e-10   9.79159198e-10   9.80702963e-10
    9.82335990e-10   9.84045956e-10]
 [  9.75172609e-10   9.74004655e-10   9.73146785e-10   9.72806502e-10
    9.73106595e-10   9.74001102e-10   9.75039827e-10   9.76594361e-10
    9.78244707e-10   9.79963000e-10]
 [  9.72970593e-10   9.71798420e-10   9.70939440e-10   9.70600933e-10
    9.7091

<string>:182: RuntimeWarning: divide by zero encountered in log10


In [247]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.28
0.28
0.28
0.28
0.28
0.28
0.28
0.28
0.28
0.28
0.28
0.28


In [18]:
%%time
%run ../optimize_pkg_2.py
N = 6
tSNR_range = np.arange(19.7, 19.81, 0.01)
rSNR3_range = np.arange(1.25, 1.271, 0.01)
rSNRdu_range = [0.28]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (11, 3) size of matrix 33
[[  1.10472387e-09   1.10512566e-09   1.10697240e-09]
 [  1.09048748e-09   1.09078679e-09   1.09252718e-09]
 [  1.07644105e-09   1.07663933e-09   1.07827480e-09]
 [  1.06258180e-09   1.06268061e-09   1.06421294e-09]
 [  1.04890707e-09   1.04890807e-09   1.05033859e-09]
 [  1.03541475e-09   1.03531939e-09   1.03664977e-09]
 [  1.02210196e-09   1.02191211e-09   1.02314357e-09]
 [  1.00896658e-09   1.00868314e-09   1.00981756e-09]
 [  9.96006166e-10   9.95631133e-10   9.96669858e-10]
 [  9.83218396e-10   9.82752879e-10   9.83697457e-10]
 [  9.70601044e-10   9.70046710e-10   9.70898473e-10]]
CPU times: user 10.4 s, sys: 90.1 ms, total: 10.5 s
Wall time: 12.6 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [19]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.25
1.25
1.25
1.25
1.25
1.26
1.26
1.26
1.26
1.26
1.26


## N = 7

In [236]:
%%time
%run ../optimize_pkg_2.py
N = 7
tSNR_range = [17.8] # 17.79
rSNR3_range = np.arange(1.45, 1.51, 0.01) # 1.48
rSNRdu_range = np.arange(0.35, 0.45, 0.01) # 0.4

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (7, 11) size of matrix 77
[[  1.00469555e-09   1.00464237e-09   1.00505637e-09   1.00589215e-09
    1.00730724e-09   1.00893272e-09   1.01077702e-09   1.01290731e-09
    1.01555619e-09   1.01817332e-09   1.02093289e-09]
 [  9.93167326e-10   9.93108040e-10   9.93399252e-10   9.94356930e-10
    9.95777572e-10   9.97402383e-10   9.99247796e-10   1.00138031e-09
    1.00390896e-09   1.00665920e-09   1.00942232e-09]
 [  9.84528015e-10   9.84478610e-10   9.84886728e-10   9.85724613e-10
    9.87284587e-10   9.88684912e-10   9.90764137e-10   9.92903870e-10
    9.95323934e-10   9.98205851e-10   1.00097775e-09]
 [  9.78484294e-10   9.78433445e-10   9.78850334e-10   9.79822667e-10
    9.81402959e-10   9.82808057e-10   9.84899495e-10   9.87050441e-10
    9.89481608e-10   9.92384619e-10   9.95170168e-10]
 [  9.74800352e-10   9.74750836e-10   9.75173386e-10   9.75915015e-10
    9.77767312e-10   9.79180514e-10   9.81287274e-10   9.83453541e-10
    9.85898918e-10   9.88701010e-10   9.91630333e-1

<string>:182: RuntimeWarning: divide by zero encountered in log10


In [237]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.36
0.36
0.36
0.36
0.36
0.36
0.36


In [20]:
%%time
%run ../optimize_pkg_2.py
N = 7
tSNR_range = np.arange(17.78, 17.791, 0.01)
rSNR3_range = np.arange(1.49, 1.521, 0.01)
rSNRdu_range = [0.36]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (2, 4) size of matrix 8
[[  1.00382191e-09   1.00229380e-09   1.00243014e-09   1.00399955e-09]
 [  9.89174187e-10   9.87529614e-10   9.87544491e-10   9.88988225e-10]]
CPU times: user 3.62 s, sys: 52.5 ms, total: 3.67 s
Wall time: 4.06 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [21]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.5
1.5


## N = 9

In [5]:
%%time
%run ../optimize_pkg_2.py
N = 9
tSNR_range = np.arange(15.3, 15.4, 0.1)
rSNR3_range = np.arange(2.08, 2.12, 0.01)
rSNRdu_range = np.arange(0.6, 0.72, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (5, 12) size of matrix 60
[[  9.33659372e-10   9.32670496e-10   9.32243616e-10   9.32344868e-10
    9.32904642e-10   9.33872091e-10   9.35179822e-10   9.36781097e-10
    9.38969791e-10   9.41313916e-10   9.43985667e-10   9.46977274e-10]
 [  9.30548638e-10   9.29550548e-10   9.29118116e-10   9.29221144e-10
    9.29784916e-10   9.30758914e-10   9.32076971e-10   9.33689348e-10
    9.35847178e-10   9.38263134e-10   9.40957090e-10   9.43930267e-10]
 [  9.29268884e-10   9.28218280e-10   9.27827148e-10   9.27883437e-10
    9.28459976e-10   9.29485600e-10   9.30816535e-10   9.32442568e-10
    9.34572197e-10   9.37063094e-10   9.39781808e-10   9.42731004e-10]
 [  9.29595623e-10   9.28536581e-10   9.28144894e-10   9.28153998e-10
    9.28789268e-10   9.29775590e-10   9.31122290e-10   9.32813826e-10
    9.34966771e-10   9.37434352e-10   9.40232781e-10   9.43209733e-10]
 [  9.31333233e-10   9.30266530e-10   9.29831656e-10   9.29888833e-10
    9.30534538e-10   9.31532962e-10   9.32895761e-10 

<string>:182: RuntimeWarning: divide by zero encountered in log10


In [6]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.62
0.62
0.62
0.62
0.62


In [22]:
%%time
%run ../optimize_pkg_2.py
N = 9
tSNR_range = np.arange(15.24, 15.28, 0.01)
rSNR3_range = np.arange(2.08, 2.12, 0.01)
rSNRdu_range = [0.62]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (4, 5) size of matrix 20
[[  1.03821163e-09   1.03608289e-09   1.03586562e-09   1.03729170e-09
    1.04016196e-09]
 [  1.01968611e-09   1.01741726e-09   1.01696851e-09   1.01819908e-09
    1.02086894e-09]
 [  1.00151532e-09   9.99067495e-10   9.98434002e-10   9.99473837e-10
    1.00194741e-09]
 [  9.83692905e-10   9.81069892e-10   9.80298731e-10   9.81108750e-10
    9.83390036e-10]]
CPU times: user 17.2 s, sys: 162 ms, total: 17.4 s
Wall time: 20 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [23]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.1
2.1
2.1
2.1


## N = 10

In [29]:
%%time
N = 10
tSNR_range = np.arange(14.4, 14.41, 0.1)
rSNR3_range = np.arange(2.42, 2.46, 0.01)
rSNRdu_range = np.arange(0.75, 0.86, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (5, 11) size of matrix 55
[[  1.14443854e-09   1.14038279e-09   1.13709209e-09   1.13454612e-09
    1.13269794e-09   1.13155973e-09   1.13102261e-09   1.13111476e-09
    1.13170040e-09   1.13277054e-09   1.13462995e-09]
 [  1.14334231e-09   1.13928089e-09   1.13595955e-09   1.13338949e-09
    1.13149579e-09   1.13037557e-09   1.12983245e-09   1.12986198e-09
    1.13051457e-09   1.13159426e-09   1.13347209e-09]
 [  1.14422916e-09   1.14012899e-09   1.13677734e-09   1.13414989e-09
    1.13227316e-09   1.13111132e-09   1.13059717e-09   1.13059484e-09
    1.13128884e-09   1.13234533e-09   1.13421117e-09]
 [  1.14674170e-09   1.14270626e-09   1.13932452e-09   1.13667287e-09
    1.13478227e-09   1.13358434e-09   1.13309662e-09   1.13309573e-09
    1.13373710e-09   1.13486864e-09   1.13668874e-09]
 [  1.15088750e-09   1.14681775e-09   1.14340670e-09   1.14073206e-09
    1.13882792e-09   1.13755405e-09   1.13713428e-09   1.13710286e-09
    1.13778775e-09   1.13893628e-09   1.14077814e-0

In [30]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.81
0.81
0.82
0.82
0.82


In [24]:
%%time
%run ../optimize_pkg_2.py
N = 10
tSNR_range = np.arange(14.45, 14.48, 0.01)
rSNR3_range = np.arange(2.42, 2.451, 0.01)
rSNRdu_range = [0.82]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (4, 4) size of matrix 16
[[  1.02559139e-09   1.02324549e-09   1.02275410e-09   1.02402931e-09]
 [  1.00578834e-09   1.00322717e-09   1.00258069e-09   1.00356146e-09]
 [  9.86400628e-10   9.83629289e-10   9.82766313e-10   9.83557458e-10]
 [  9.67420144e-10   9.64444302e-10   9.63368940e-10   9.63943148e-10]]
CPU times: user 18.8 s, sys: 266 ms, total: 19 s
Wall time: 21.3 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [25]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.44
2.44
2.44
2.44


## N = 11

In [50]:
%%time
N = 11
tSNR_range = np.arange(13.8, 13.81, 0.1)
rSNR3_range = np.arange(2.67, 2.74, 0.01)
rSNRdu_range = np.arange(0.85, 0.96, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (8, 11) size of matrix 88
[[  9.51982049e-10   9.47007361e-10   9.42773859e-10   9.39265554e-10
    9.36392741e-10   9.34103239e-10   9.32422362e-10   9.31208777e-10
    9.30513666e-10   9.30244104e-10   9.30629573e-10]
 [  9.47421808e-10   9.42388390e-10   9.38088940e-10   9.34583078e-10
    9.31674737e-10   9.29333499e-10   9.27653732e-10   9.26399624e-10
    9.25713839e-10   9.25433508e-10   9.25801213e-10]
 [  9.44899936e-10   9.39860079e-10   9.35512778e-10   9.31921318e-10
    9.29026189e-10   9.26586585e-10   9.24888610e-10   9.23660926e-10
    9.22988241e-10   9.22699028e-10   9.23067400e-10]
 [  9.44265555e-10   9.39083367e-10   9.34754052e-10   9.31128508e-10
    9.28219057e-10   9.25750365e-10   9.24032850e-10   9.22790067e-10
    9.22108168e-10   9.21811738e-10   9.22074528e-10]
 [  9.45249101e-10   9.40034051e-10   9.35659328e-10   9.31993371e-10
    9.29006871e-10   9.26533739e-10   9.24820109e-10   9.23563670e-10
    9.22850463e-10   9.22571131e-10   9.22834031e-1

In [51]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

0.94
0.94
0.94
0.94
0.94
0.94
0.94
0.94


In [26]:
%%time
%run ../optimize_pkg_2.py
N = 11
tSNR_range = np.arange(13.75, 13.81, 0.01)
rSNR3_range = np.arange(2.67, 2.73, 0.01)
rSNRdu_range = [0.94]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (7, 7) size of matrix 49
[[  1.03131903e-09   1.02768349e-09   1.02616382e-09   1.02652820e-09
    1.02857500e-09   1.03210218e-09   1.03699715e-09]
 [  1.01017017e-09   1.00628639e-09   1.00451025e-09   1.00461128e-09
    1.00638742e-09   1.00965902e-09   1.01424735e-09]
 [  9.89501370e-10   9.85376225e-10   9.83350290e-10   9.83194193e-10
    9.84705650e-10   9.87706583e-10   9.92040006e-10]
 [  9.69302194e-10   9.64942126e-10   9.62672608e-10   9.62265601e-10
    9.63519486e-10   9.66255631e-10   9.70317937e-10]
 [  9.49561874e-10   9.44972101e-10   9.42465661e-10   9.41814293e-10
    9.42816714e-10   9.45295175e-10   9.49092915e-10]
 [  9.30269417e-10   9.25456156e-10   9.22718790e-10   9.21829280e-10
    9.22586452e-10   9.24812782e-10   9.28352728e-10]
 [  9.11460130e-10   9.06383968e-10   9.03421782e-10   9.02299568e-10
    9.02817821e-10   9.04799013e-10   9.08086939e-10]]
CPU times: user 1min 6s, sys: 320 ms, total: 1min 6s
Wall time: 1min 8s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [27]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.69
2.69
2.7
2.7
2.7
2.7
2.7


## N = 12

In [77]:
%%time
N = 12
tSNR_range = np.arange(13.24, 13.26, 0.1)
rSNR3_range = np.arange(2.99, 3.01, 0.01)
rSNRdu_range = np.arange(1.08, 1.12, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 5) size of matrix 10
[[  1.00197028e-09   1.00170250e-09   1.00184683e-09   1.00252229e-09
    1.00377817e-09]
 [  1.00153008e-09   1.00128861e-09   1.00141684e-09   1.00210729e-09
    1.00333919e-09]]
CPU times: user 17.5 s, sys: 94.3 ms, total: 17.6 s
Wall time: 18.4 s


In [78]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.09
1.09


In [28]:
%%time
%run ../optimize_pkg_2.py
N = 12
tSNR_range = np.arange(13.2, 13.26, 0.01)
rSNR3_range = np.arange(2.98, 3.02, 0.01)
rSNRdu_range = [1.09]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (7, 5) size of matrix 35
[[  1.09787157e-09   1.09668963e-09   1.09750697e-09   1.10014065e-09
    1.10431819e-09]
 [  1.07355991e-09   1.07205933e-09   1.07255205e-09   1.07485076e-09
    1.07869635e-09]
 [  1.04983999e-09   1.04804854e-09   1.04822329e-09   1.05018005e-09
    1.05372477e-09]
 [  1.02669995e-09   1.02460873e-09   1.02447428e-09   1.02611464e-09
    1.02936737e-09]
 [  1.00412523e-09   1.00174224e-09   1.00132325e-09   1.00263842e-09
    1.00557340e-09]
 [  9.82128046e-10   9.79432979e-10   9.78722547e-10   9.79753167e-10
    9.82363302e-10]
 [  9.60640789e-10   9.57670943e-10   9.56674628e-10   9.57428248e-10
    9.59723190e-10]]
CPU times: user 1min 10s, sys: 492 ms, total: 1min 10s
Wall time: 1min 15s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [29]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.99
2.99
2.99
3.0
3.0
3.0
3.0


## N = 13

In [94]:
%%time
N = 13
tSNR_range = np.arange(12.7, 12.71, 0.1)
rSNR3_range = np.arange(3.1, 3.21, 0.1)
rSNRdu_range = np.arange(1.05, 1.15, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 10) size of matrix 20
[[  1.00175468e-09   9.98136351e-10   9.95238558e-10   9.92846028e-10
    9.91018823e-10   9.89711202e-10   9.88909177e-10   9.88624294e-10
    9.88867432e-10   9.89550997e-10]
 [  9.94778704e-10   9.90590054e-10   9.87173676e-10   9.84409443e-10
    9.82258608e-10   9.80719173e-10   9.79795134e-10   9.79370585e-10
    9.79509585e-10   9.80179271e-10]]
CPU times: user 47.3 s, sys: 322 ms, total: 47.6 s
Wall time: 49.9 s


In [95]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.12
1.12


In [30]:
%%time
%run ../optimize_pkg_2.py
N = 13
tSNR_range = np.arange(12.68, 12.72, 0.01)
rSNR3_range = np.arange(3.14, 3.161, 0.01)
rSNRdu_range = [1.12]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (5, 3) size of matrix 15
[[  1.00856901e-09   1.00813669e-09   1.00955955e-09]
 [  9.84892945e-10   9.84113124e-10   9.85190263e-10]
 [  9.61820845e-10   9.60705182e-10   9.61447588e-10]
 [  9.39340383e-10   9.37931288e-10   9.38324307e-10]
 [  9.17456999e-10   9.15740594e-10   9.15805876e-10]]
CPU times: user 41 s, sys: 428 ms, total: 41.4 s
Wall time: 46.3 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [31]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

3.15
3.15
3.15
3.15
3.15


## N = 14

In [118]:
%%time
N = 14
tSNR_range = np.arange(12.26, 12.28, 0.1)
rSNR3_range = np.arange(3.35, 3.361, 0.01)
rSNRdu_range = np.arange(1.15, 1.25, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 11) size of matrix 22
[[  1.02225250e-09   1.01882380e-09   1.01610398e-09   1.01402908e-09
    1.01249853e-09   1.01154374e-09   1.01116515e-09   1.01127906e-09
    1.01187414e-09   1.01297437e-09   1.01456599e-09]
 [  1.02398900e-09   1.02051900e-09   1.01773756e-09   1.01560127e-09
    1.01405051e-09   1.01309139e-09   1.01269049e-09   1.01280706e-09
    1.01341013e-09   1.01452668e-09   1.01612507e-09]]
CPU times: user 1min 3s, sys: 404 ms, total: 1min 3s
Wall time: 1min 6s


In [119]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.21
1.21


In [32]:
%%time
%run ../optimize_pkg_2.py
N = 14
tSNR_range = np.arange(12.26, 12.28, 0.01)
rSNR3_range = np.arange(3.34, 3.361, 0.01)
rSNRdu_range = [1.21]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (2, 3) size of matrix 6
[[  1.01163944e-09   1.01125464e-09   1.01277009e-09]
 [  9.86702720e-10   9.85946214e-10   9.87083304e-10]]
CPU times: user 17.5 s, sys: 233 ms, total: 17.7 s
Wall time: 18.4 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [33]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

3.35
3.35


## N = 15

In [163]:
%%time
N = 15
tSNR_range = np.arange(12.2, 12.21, 0.1)
rSNR3_range = np.arange(3.83, 3.861, 0.01)
rSNRdu_range = np.arange(1.51, 1.54, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (4, 4) size of matrix 16
[[  9.62063096e-10   9.61703384e-10   9.61782542e-10   9.62332103e-10]
 [  9.59127222e-10   9.58732649e-10   9.58819579e-10   9.59345825e-10]
 [  9.58216173e-10   9.57809720e-10   9.57879109e-10   9.58407465e-10]
 [  9.59157420e-10   9.58752300e-10   9.58807700e-10   9.59323065e-10]]
CPU times: user 57.3 s, sys: 357 ms, total: 57.7 s
Wall time: 1min


In [164]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.52
1.52
1.52
1.52


In [34]:
%%time
%run ../optimize_pkg_2.py
N = 15
tSNR_range = np.arange(12.18, 12.191, 0.01)
rSNR3_range = np.arange(3.84, 3.861, 0.01)
rSNRdu_range = [1.52]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (2, 3) size of matrix 6
[[  1.00985564e-09   1.00975672e-09   1.01153674e-09]
 [  9.83992443e-10   9.83470083e-10   9.84819115e-10]]
CPU times: user 22.7 s, sys: 355 ms, total: 23.1 s
Wall time: 24.1 s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [35]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

3.85
3.85


## N = 16

In [161]:
%%time
N = 16
tSNR_range = np.arange(11.6, 11.61, 0.1)
rSNR3_range = np.arange(3.7, 3.91, 0.1)
rSNRdu_range = np.arange(1.38, 1.48, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (3, 11) size of matrix 33
[[  1.24098531e-09   1.24093003e-09   1.24136079e-09   1.24226207e-09
    1.24363786e-09   1.24549915e-09   1.24776167e-09   1.25043575e-09
    1.25360466e-09   1.25710864e-09   1.26103972e-09]
 [  1.14486398e-09   1.14460408e-09   1.14488008e-09   1.14565113e-09
    1.14695908e-09   1.14881160e-09   1.15117393e-09   1.15400423e-09
    1.15732701e-09   1.16114973e-09   1.16536636e-09]
 [  1.26212685e-09   1.26169597e-09   1.26196564e-09   1.26288902e-09
    1.26441446e-09   1.26652921e-09   1.26924105e-09   1.27253807e-09
    1.27639355e-09   1.28082989e-09   1.28578936e-09]]
CPU times: user 2min 22s, sys: 1.2 s, total: 2min 23s
Wall time: 2min 31s


In [162]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.39
1.39
1.39


In [36]:
%%time
%run ../optimize_pkg_2.py
N = 16
tSNR_range = np.arange(11.64, 11.69, 0.01)
rSNR3_range = np.arange(3.77, 3.83, 0.01)
rSNRdu_range = [1.39]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (5, 7) size of matrix 35
[[  1.02819597e-09   1.02453701e-09   1.02317455e-09   1.02391962e-09
    1.02660902e-09   1.03105080e-09   1.03714326e-09]
 [  1.00164732e-09   9.97545491e-10   9.95716509e-10   9.95971861e-10
    9.98167549e-10   1.00211872e-09   1.00768993e-09]
 [  9.75918901e-10   9.71370318e-10   9.69100578e-10   9.68891745e-10
    9.70599601e-10   9.74069714e-10   9.79133108e-10]
 [  9.50965862e-10   9.45998391e-10   9.43287448e-10   9.42639522e-10
    9.43879086e-10   9.46872247e-10   9.51468460e-10]
 [  9.26774657e-10   9.21414278e-10   9.18270904e-10   9.17193321e-10
    9.17987353e-10   9.20510002e-10   9.24639032e-10]]
CPU times: user 2min 33s, sys: 854 ms, total: 2min 34s
Wall time: 2min 39s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [37]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

3.79
3.79
3.8
3.8
3.8


## N = 17

In [188]:
%%time
N = 17
tSNR_range = np.arange(11.5, 11.51, 0.1)
rSNR3_range = np.arange(4.0, 4.21, 0.1)
rSNRdu_range = np.arange(1.55, 1.65, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (3, 10) size of matrix 30
[[  1.26956201e-09   1.26798183e-09   1.26686095e-09   1.26622268e-09
    1.26603239e-09   1.26629096e-09   1.26695754e-09   1.26803257e-09
    1.26953026e-09   1.27141431e-09]
 [  1.07538700e-09   1.07316944e-09   1.07154319e-09   1.07043741e-09
    1.06982845e-09   1.06975329e-09   1.07014531e-09   1.07100850e-09
    1.07234666e-09   1.07412756e-09]
 [  1.14314058e-09   1.14037857e-09   1.13833143e-09   1.13690179e-09
    1.13608156e-09   1.13587140e-09   1.13624987e-09   1.13718290e-09
    1.13864429e-09   1.14062337e-09]]
CPU times: user 2min 42s, sys: 1.57 s, total: 2min 43s
Wall time: 2min 53s


In [189]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.59
1.6
1.6


In [38]:
%%time
%run ../optimize_pkg_2.py
N = 17
tSNR_range = np.arange(11.52, 11.57, 0.01)
rSNR3_range = np.arange(4.1, 4.151, 0.01)
rSNRdu_range = [1.6]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (6, 6) size of matrix 36
[[  1.01306030e-09   1.01017095e-09   1.00951947e-09   1.01093178e-09
    1.01425135e-09   1.01932440e-09]
 [  9.85912907e-10   9.82532389e-10   9.81367543e-10   9.82253723e-10
    9.85034054e-10   9.89561544e-10]
 [  9.59626489e-10   9.55773904e-10   9.54116119e-10   9.54499257e-10
    9.56753343e-10   9.60748259e-10]
 [  9.34194944e-10   9.29873401e-10   9.27747879e-10   9.27634525e-10
    9.29386124e-10   9.32863120e-10]
 [  9.09570974e-10   9.04800901e-10   9.02211417e-10   9.01631658e-10
    9.02889430e-10   9.05866937e-10]
 [  8.85726936e-10   8.80531759e-10   8.77494966e-10   8.76460571e-10
    8.77251161e-10   8.79737505e-10]]
CPU times: user 3min 7s, sys: 780 ms, total: 3min 7s
Wall time: 3min 11s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [39]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

4.12
4.12
4.12
4.13
4.13
4.13


## N = 18

In [209]:
%%time
N = 18
tSNR_range = [11.45]
rSNR3_range = np.arange(4.46, 4.471, 0.01)
rSNRdu_range = np.arange(1.75, 1.85, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 11) size of matrix 22
[[  9.79492709e-10   9.78387482e-10   9.77770198e-10   9.77571357e-10
    9.77808279e-10   9.78457315e-10   9.79545445e-10   9.80989068e-10
    9.82841031e-10   9.85050930e-10   9.87655735e-10]
 [  9.79484938e-10   9.78343739e-10   9.77693926e-10   9.77486092e-10
    9.77705916e-10   9.78348846e-10   9.79432979e-10   9.80893367e-10
    9.82760318e-10   9.84996973e-10   9.87627868e-10]]
CPU times: user 2min 21s, sys: 1.35 s, total: 2min 23s
Wall time: 2min 36s


In [210]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.78
1.78


In [40]:
%%time
%run ../optimize_pkg_2.py
N = 18
tSNR_range = np.arange(11.43, 11.48, 0.01)
rSNR3_range = np.arange(4.45, 4.491, 0.01)
rSNRdu_range = [1.78]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (6, 5) size of matrix 30
[[  1.03711584e-09   1.03597630e-09   1.03698916e-09   1.04001863e-09
    1.04492037e-09]
 [  1.00817665e-09   1.00647080e-09   1.00691189e-09   1.00933217e-09
    1.01361708e-09]
 [  9.80201253e-10   9.77949832e-10   9.77830927e-10   9.79682224e-10
    9.83367721e-10]
 [  9.53171431e-10   9.50385881e-10   9.49718415e-10   9.51020818e-10
    9.54134660e-10]
 [  9.27037114e-10   9.23741528e-10   9.22554810e-10   9.23312871e-10
    9.25883259e-10]
 [  9.01770214e-10   8.97989572e-10   8.96297925e-10   8.96536512e-10
    8.98577990e-10]]
CPU times: user 3min 10s, sys: 737 ms, total: 3min 11s
Wall time: 3min 14s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [41]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

4.46
4.46
4.47
4.47
4.47
4.47


## N = 19

In [223]:
%%time
N = 19
tSNR_range = [11.5]
rSNR3_range = np.arange(4.88, 4.92, 0.01)
rSNRdu_range = np.arange(2.05, 2.15, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (5, 11) size of matrix 55
[[  9.91856930e-10   9.91869031e-10   9.92253169e-10   9.93059190e-10
    9.94239580e-10   9.95741489e-10   9.97610550e-10   9.99859417e-10
    1.00241238e-09   1.00529762e-09   1.00851072e-09]
 [  9.86341897e-10   9.86333681e-10   9.86702831e-10   9.87481541e-10
    9.88681914e-10   9.90182158e-10   9.92064431e-10   9.94319627e-10
    9.96898231e-10   9.99817007e-10   1.00306463e-09]
 [  9.83186976e-10   9.83160331e-10   9.83511605e-10   9.84276771e-10
    9.85479365e-10   9.86994819e-10   9.88888416e-10   9.91165150e-10
    9.93765958e-10   9.96719818e-10   9.99999861e-10]
 [  9.82230408e-10   9.82182446e-10   9.82530390e-10   9.83285786e-10
    9.84477944e-10   9.86007720e-10   9.87931514e-10   9.90228455e-10
    9.92853466e-10   9.95838301e-10   9.99169303e-10]
 [  9.83330861e-10   9.83260806e-10   9.83589876e-10   9.84353821e-10
    9.85553417e-10   9.87091742e-10   9.89030191e-10   9.91353444e-10
    9.94014537e-10   9.97040561e-10   1.00040731e-0

In [224]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.05
2.06
2.06
2.06
2.06


In [42]:
%%time
%run ../optimize_pkg_2.py
N = 19
tSNR_range = np.arange(11.48, 11.511, 0.01)
rSNR3_range = np.arange(4.89, 4.921, 0.01)
rSNRdu_range = [2.06]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (4, 4) size of matrix 16
[[  1.04483999e-09   1.04280762e-09   1.04301567e-09   1.04532527e-09]
 [  1.01536390e-09   1.01272268e-09   1.01229902e-09   1.01396147e-09]
 [  9.86906667e-10   9.83683579e-10   9.82660620e-10   9.83696680e-10]
 [  9.59432978e-10   9.55646340e-10   9.54045065e-10   9.54479940e-10]]
CPU times: user 2min 2s, sys: 563 ms, total: 2min 3s
Wall time: 2min 5s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [43]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

4.9
4.91
4.91
4.91


## N = 20

In [273]:
%%time
N = 20
tSNR_range = [11.2]
rSNR3_range = np.arange(4.9, 5.01, 0.1)
rSNRdu_range = np.arange(1.85, 1.95, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 10) size of matrix 20
[[  7.68416442e-10   7.65721264e-10   7.63435426e-10   7.61538943e-10
    7.60028818e-10   7.58867857e-10   7.58065055e-10   7.57601093e-10
    7.57462759e-10   7.57686136e-10]
 [  8.60103766e-10   8.56689719e-10   8.53785265e-10   8.51382853e-10
    8.49429638e-10   8.47935389e-10   8.46862247e-10   8.46206105e-10
    8.45967518e-10   8.46130610e-10]]
CPU times: user 3min 13s, sys: 1.99 s, total: 3min 15s
Wall time: 3min 30s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [274]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

1.93
1.93


In [44]:
%%time
%run ../optimize_pkg_2.py
N = 20
tSNR_range = np.arange(11.09, 11.121, 0.01)
rSNR3_range = np.arange(4.85, 4.91, 0.01)
rSNRdu_range = [1.93]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (4, 7) size of matrix 28
[[  1.05658315e-09   1.05770115e-09   1.06096276e-09   1.06623110e-09
    1.07340459e-09   1.08236586e-09   1.09301246e-09]
 [  1.02502296e-09   1.02544551e-09   1.02799413e-09   1.03253084e-09
    1.03894715e-09   1.04713371e-09   1.05698972e-09]
 [  9.94595628e-10   9.94351379e-10   9.96214777e-10   1.00005304e-09
    1.00573838e-09   1.01317765e-09   1.02226261e-09]
 [  9.65258651e-10   9.64383906e-10   9.65584168e-10   9.68740754e-10
    9.73736647e-10   9.80448500e-10   9.88796045e-10]]
CPU times: user 4min 10s, sys: 932 ms, total: 4min 11s
Wall time: 4min 15s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [45]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

4.85
4.85
4.86
4.86


## N = 21

In [329]:
%%time
N = 21
tSNR_range = [11.3]
rSNR3_range = np.arange(5.4, 5.42, 0.01) # 5.1 below 4.9 below 4.8
rSNRdu_range = np.arange(2.21, 2.261, 0.01) # 2.1 below 1.9, 2.0

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (2, 6) size of matrix 12
[[  1.01439646e-09   1.01261943e-09   1.01129827e-09   1.01038489e-09
    1.00987207e-09   1.00975883e-09]
 [  1.01560527e-09   1.01376285e-09   1.01238740e-09   1.01143993e-09
    1.01089992e-09   1.01076136e-09]]
CPU times: user 2min 15s, sys: 1.17 s, total: 2min 16s
Wall time: 2min 27s


In [330]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.26
2.26


In [46]:
%%time
%run ../optimize_pkg_2.py
N = 21
tSNR_range = np.arange(11.3, 11.34, 0.01)
rSNR3_range = np.arange(5.39, 5.421, 0.01)
rSNRdu_range = [2.26]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (4, 4) size of matrix 16
[[  1.01182385e-09   1.01057573e-09   1.01151143e-09   1.01450803e-09]
 [  9.81998149e-10   9.80068693e-10   9.80301729e-10   9.82564030e-10]
 [  9.53283119e-10   9.50700296e-10   9.50249990e-10   9.51816848e-10]
 [  9.25636345e-10   9.22422361e-10   9.21329901e-10   9.22217192e-10]]
CPU times: user 2min 50s, sys: 693 ms, total: 2min 51s
Wall time: 2min 55s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [47]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

5.4
5.4
5.41
5.41


## N = 22

In [344]:
%%time
N = 22
tSNR_range = [11]
rSNR3_range = np.arange(5.38, 5.411, 0.01)
rSNRdu_range = np.arange(2.15, 2.251, 0.02) # 2.3 < 2.4

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (4, 6) size of matrix 24
[[  1.01258824e-09   1.01093289e-09   1.01088393e-09   1.01235120e-09
    1.01524078e-09   1.01956510e-09]
 [  1.01427466e-09   1.01252784e-09   1.01244302e-09   1.01389130e-09
    1.01680753e-09   1.02117714e-09]
 [  1.01804842e-09   1.01623576e-09   1.01609998e-09   1.01754416e-09
    1.02048525e-09   1.02490527e-09]
 [  1.02381248e-09   1.02192588e-09   1.02175080e-09   1.02319220e-09
    1.02616671e-09   1.03064590e-09]]
CPU times: user 4min 59s, sys: 2.21 s, total: 5min 1s
Wall time: 5min 22s


In [345]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.19
2.19
2.19
2.19


In [48]:
%%time
%run ../optimize_pkg_2.py
N = 22
tSNR_range = np.arange(11., 11.05, 0.01)
rSNR3_range = np.arange(5.37, 5.421, 0.01)
rSNRdu_range = [2.19]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (6, 6) size of matrix 36
[[  1.01252651e-09   1.01178266e-09   1.01326902e-09   1.01685860e-09
    1.02244824e-09   1.02993369e-09]
 [  9.81810189e-10   9.80331483e-10   9.81063786e-10   9.83864212e-10
    9.88647275e-10   9.95302840e-10]
 [  9.52277590e-10   9.50093892e-10   9.50092005e-10   9.52148804e-10
    9.56154489e-10   9.62008473e-10]
 [  9.23874532e-10   9.21012488e-10   9.20315935e-10   9.21658083e-10
    9.24910926e-10   9.30000965e-10]
 [  8.96568819e-10   8.93055296e-10   8.91683283e-10   8.92328877e-10
    8.94881280e-10   8.99223584e-10]
 [  8.70308825e-10   8.66164918e-10   8.64150973e-10   8.64132876e-10
    8.65999161e-10   8.69637140e-10]]
CPU times: user 7min 19s, sys: 1.76 s, total: 7min 21s
Wall time: 7min 28s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [49]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

5.38
5.38
5.39
5.39
5.39
5.4


## N = 23

In [361]:
%%time
N = 23
tSNR_range = [11.2]
rSNR3_range = np.arange(5.8, 6.01, 0.1)
rSNRdu_range = np.arange(2.48, 2.581, 0.02) # 2.3 < 2.4

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (3, 6) size of matrix 18
[[  3.04009840e-09   3.03504488e-09   3.03208025e-09   3.03106795e-09
    3.03191861e-09   3.03454695e-09]
 [  2.03106187e-09   2.02217632e-09   2.01566852e-09   2.01133965e-09
    2.00915196e-09   2.00896200e-09]
 [  1.75601722e-09   1.74352299e-09   1.73395531e-09   1.72706893e-09
    1.72276571e-09   1.72090420e-09]]
CPU times: user 4min 55s, sys: 2.09 s, total: 4min 57s
Wall time: 5min 13s


In [362]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.54
2.58
2.58


In [50]:
%%time
%run ../optimize_pkg_2.py
N = 23
tSNR_range = np.arange(11.37, 11.381, 0.01)
rSNR3_range = np.arange(6.06, 6.10, 0.01)
rSNRdu_range = [2.56] # 2.56 for 11

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (2, 5) size of matrix 10
[[  1.01174646e-09   1.00948372e-09   1.00949149e-09   1.01163888e-09
    1.01584163e-09]
 [  9.81693726e-10   9.78678472e-10   9.77900871e-10   9.79250347e-10
    9.82612436e-10]]
CPU times: user 2min 32s, sys: 681 ms, total: 2min 33s
Wall time: 2min 35s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [51]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

6.07
6.08


## N = 24

In [54]:
%%time
N = 24
tSNR_range = [11.11]
rSNR3_range = np.arange(6.05, 6.11, 0.01)
rSNRdu_range = np.arange(2.45, 2.551, 0.02) # 2.3 < 2.4

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (7, 6) size of matrix 42
[[  1.01103703e-09   1.00639552e-09   1.00324038e-09   1.00155606e-09
    1.00126119e-09   1.00233200e-09]
 [  1.01131814e-09   1.00653108e-09   1.00324626e-09   1.00148456e-09
    1.00114350e-09   1.00219710e-09]
 [  1.01381137e-09   1.00886866e-09   1.00546538e-09   1.00362385e-09
    1.00323072e-09   1.00427278e-09]
 [  1.01840480e-09   1.01330699e-09   1.00978936e-09   1.00786068e-09
    1.00742725e-09   1.00845976e-09]
 [  1.02501818e-09   1.01975939e-09   1.01612307e-09   1.01411446e-09
    1.01363817e-09   1.01467168e-09]
 [  1.03355680e-09   1.02813291e-09   1.02438891e-09   1.02229736e-09
    1.02177411e-09   1.02280617e-09]
 [  1.04395137e-09   1.03836872e-09   1.03450193e-09   1.03233455e-09
    1.03177566e-09   1.03280229e-09]]
CPU times: user 13min 50s, sys: 8.38 s, total: 13min 58s
Wall time: 16min 3s


In [55]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

2.53
2.53
2.53
2.53
2.53
2.53
2.53


In [52]:
%%time
%run ../optimize_pkg_2.py
N = 24
tSNR_range = np.arange(11.11, 11.121, 0.01) # 11.10 fails
rSNR3_range = np.arange(6.05, 6.081, 0.01) # 6.08 better than 6.09
rSNRdu_range = [2.53] # 2.56 for 11

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (5, 4) size of matrix 20
[[  1.00126252e-09   1.00114472e-09   1.00323050e-09   1.00742803e-09]
 [  9.70044378e-10   9.69103797e-10   9.70343139e-10   9.73664815e-10]
 [  9.40102551e-10   9.38373379e-10   9.38803923e-10   9.41281830e-10]
 [  9.11373088e-10   9.08895958e-10   9.08549236e-10   9.10220788e-10]
 [  8.83816798e-10   8.80616913e-10   8.79526119e-10   8.80429063e-10]]
CPU times: user 5min 30s, sys: 1.19 s, total: 5min 31s
Wall time: 5min 37s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [53]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

6.06
6.06
6.06
6.07
6.07


## N = 25

In [ ]:
%%time
N = 25
tSNR_range = [12.1]
rSNR3_range = np.arange(6.05, 6.151, 0.05)
rSNRdu_range = np.arange(2.45, 2.551, 0.02) # 2.3 < 2.4

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result