In [1]:
%pylab inline
from __future__ import division
import scipy as sp
from scipy import stats
from scipy.signal import argrelextrema
from scipy.interpolate import interp1d
import operator as op
from decimal import *
# import pickle
# from mpl_toolkits.mplot3d import Axes3D
import mpld3
mpld3.enable_notebook()

Populating the interactive namespace from numpy and matplotlib


In [2]:
%run ../cow.py
%run ../optimize_pkg_2.py

In [3]:
filepath_down = "../data_tables/hs_rs_downlink/n"
filepath_up = "../data_tables/hs_rs_uplink/n"
protocolbit = 4*10**4
protocol_target = 10**(-9)

## N = 35

In [20]:
%%time
N = 35
tSNR_range = [13.85]
rSNR3_range = np.arange(11.05, 11.06, 0.05)
rSNRdu_range = np.arange(5.42, 5.451, 0.01)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

xn, yn (1, 4) size of matrix 4
[[  1.00752984e-09   1.03754061e-09   1.00196207e-09   9.93148230e-10]]
CPU times: user 6min 54s, sys: 2.97 s, total: 6min 57s
Wall time: 7min 35s


In [21]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

5.45


In [22]:
%%time
%run ../optimize_pkg_2.py
N = 35
tSNR_range = np.arange(13.85, 13.861, 0.01)
rSNR3_range = np.arange(11.04, 11.061, 0.01) # f(11.05 < 11.03, 11.07)
rSNRdu_range = [5.45]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

xn, yn (2, 3) size of matrix 6
[[  1.00247710e-09   9.93149007e-10   1.02917230e-09]
 [  9.82882109e-10   9.72758873e-10   9.94217264e-10]]
CPU times: user 9min 38s, sys: 3.25 s, total: 9min 41s
Wall time: 10min 18s


In [23]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

11.05
11.05
