In [1]:
%pylab inline
from __future__ import division
import scipy as sp
from scipy import stats
from scipy.signal import argrelextrema
from scipy.interpolate import interp1d
import operator as op
from decimal import *
# import pickle
from mpl_toolkits.mplot3d import Axes3D
import mpld3
# mpld3.enable_notebook()

Populating the interactive namespace from numpy and matplotlib


In [75]:
%run ../cow.py
%run ../optimize_pkg_2.py

In [3]:
filepath_down = "../data_tables/hs_rs_downlink/n"
filepath_up = "../data_tables/hs_rs_uplink/n"
protocolbit = 4*10**4
protocol_target = 10**(-9)

In [5]:
optimize_3_data = zeros((len(range(2, 36)), 6))
start_node = 2

In [7]:
%%time
%run ../optimize_3_dct.py
N = 35
d_rSNR = 0.1
d_tSNR = 0.1
tx_SNR_range = np.arange(13.8, 50, d_tSNR)
optimize_3_data[N-start_node] = optimize_3(N, rSNRdu_start[N], rSNR3_start[N], tx_SNR_range, filepath_down, filepath_up, protocolbit, d_rSNR)
print optimize_3_data[N-start_node]

<string>:182: RuntimeWarning: divide by zero encountered in log10
<string>:193: RuntimeWarning: divide by zero encountered in log10


[  1.39000000e+01   5.50000000e+00   1.10000000e+01   9.52421850e-05
   1.19899197e-02   5.59116087e-11]
CPU times: user 1h 47min 45s, sys: 41.1 s, total: 1h 48min 26s
Wall time: 1h 57min 58s


<string>:200: RuntimeWarning: divide by zero encountered in log10


In [8]:
%%time
%run ../optimize_3_dct.py
N = 35
d_rSNR = 0.1
d_tSNR = 0.1
tx_SNR_range = np.arange(13.9, 50, d_tSNR)
optimize_3_data[N-start_node] = optimize_3(N, rSNRdu_start[N], rSNR3_start[N], tx_SNR_range, filepath_down, filepath_up, protocolbit, d_rSNR)
print optimize_3_data[N-start_node]

[  1.39000000e+01   5.50000000e+00   1.10000000e+01   9.52421850e-05
   1.19899197e-02   5.59116087e-11]
CPU times: user 24min 35s, sys: 13 s, total: 24min 48s
Wall time: 28min 24s


In [9]:
%%time
%run ../optimize_3_dct.py
%run ../optimize_pkg_2.py
N = 35
d_rSNR = 0.1
d_tSNR = 0.1
tx_SNR_range = np.arange(13.9, 50, d_tSNR)
optimize_3_data[N-start_node] = optimize_3(N, rSNRdu_start[N], rSNR3_start[N], tx_SNR_range, filepath_down, filepath_up, protocolbit, d_rSNR)
print optimize_3_data[N-start_node]

[  1.39000000e+01   5.50000000e+00   1.10000000e+01   9.52421850e-05
   1.19899197e-02   5.59116087e-11]
CPU times: user 6min 34s, sys: 3.04 s, total: 6min 37s
Wall time: 6min 56s


In [13]:
%%time
%run ../optimize_3_dct.py
N = 32
d_rSNR = 0.1
d_tSNR = 0.1
tx_SNR_range = np.arange(14.2, 50, d_tSNR)
optimize_3_data[N-start_node] = optimize_3(N, 5, 11, tx_SNR_range, filepath_down, filepath_up, protocolbit, d_rSNR)
print optimize_3_data[N-start_node]

9.15956754888e-10
[  1.42000000e+01   5.00000000e+00   1.10000000e+01   3.61982254e-26
   3.01965021e-02   6.02125016e-11]
CPU times: user 55.9 s, sys: 586 ms, total: 56.5 s
Wall time: 1min 2s


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [15]:
%%time
%run ../optimize_3_dct.py
N = 32
d_rSNR = 0.1
d_tSNR = 0.1
tx_SNR_range = np.arange(14.2, 50, d_tSNR)
optimize_3_data[N-start_node] = optimize_3(N, 4.9, 11, tx_SNR_range, filepath_down, filepath_up, protocolbit, d_rSNR)
print optimize_3_data[N-start_node]

9.46741685048e-10
[  1.42000000e+01   4.90000000e+00   1.10000000e+01   1.70579888e-24
   3.53743979e-02   6.02125016e-11]
CPU times: user 57.3 s, sys: 434 ms, total: 57.8 s
Wall time: 1min 1s


In [16]:
%%time
%run ../optimize_3_dct.py
N = 32
d_rSNR = 0.1
d_tSNR = 0.1
tx_SNR_range = np.arange(14.2, 50, d_tSNR)
optimize_3_data[N-start_node] = optimize_3(N, 5.1, 11, tx_SNR_range, filepath_down, filepath_up, protocolbit, d_rSNR)
print optimize_3_data[N-start_node]

8.89631035506e-10
[  1.42000000e+01   5.10000000e+00   1.10000000e+01   6.88028427e-28
   2.56772171e-02   6.02125016e-11]
CPU times: user 50.3 s, sys: 453 ms, total: 50.8 s
Wall time: 52.6 s


In [19]:
%%time
# set tSNR, see shape of rSNRdu vs rSNR3
N = 32
tSNR = 14.2
rSNR3_range = [11]
rSNRdu_guess = 5
rSNRdu_range = np.arange(rSNRdu_guess-0.5, rSNRdu_guess+0.5+0.1, 0.1)

downbit = upbit = xorbit = 4*10**4/3
downTable = load_table(filepath_down+str(N)+extension)
downfunc = interp1d(downTable[0], downTable[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))
upTable = load_table(filepath_up+str(N)+extension)
upfunc = interp1d(upTable[0], upTable[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))

xor_table = load_table(filepath_up+str(N)+extension)
xor_func = interp1d(xor_table[0], xor_table[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))

xn, yn = len(rSNR3_range), len(rSNRdu_range)

testleah = zeros((xn, yn))
    
for xk in range(xn):
    rSNR3 = rSNR3_range[xk]
    p_add_3 = xor_func(rSNR3)
    for yk in range(yn):
        rSNRdu = rSNRdu_range[yk]
        xor_opt = xor_analysis_pruned(N, tSNR, rSNRdu, rSNR3, downfunc(rSNRdu), upfunc(rSNRdu), p_add_3)
        testleah[xk, yk] = 1 - xor_opt
#         Z[np.where(rSNR3_range==rSNR3)[0][0], np.where(rSNRdu_range==rSNRdu)[0][0]] = 1 - xor_opt

KeyboardInterrupt: 

In [47]:
%%time
# set tSNR, see shape of rSNRdu vs rSNR3
N = 8
tSNR = 16.6
rSNR3_range = np.arange(1.9, 2, 0.1)
rSNRdu_guess = 0.6
rSNRdu_range = np.arange(rSNRdu_guess-0.5, rSNRdu_guess+0.5+0.1, 0.1)
# rSNRdu_range = [0.3]

downbit = upbit = xorbit = 4*10**4/3
downTable = load_table(filepath_down+str(N)+extension)
downfunc = interp1d(downTable[0], downTable[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))
upTable = load_table(filepath_up+str(N)+extension)
upfunc = interp1d(upTable[0], upTable[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))

xor_table = load_table(filepath_up+str(N)+extension)
xor_func = interp1d(xor_table[0], xor_table[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))

xn, yn = len(rSNR3_range), len(rSNRdu_range)

testleah = zeros((xn, yn))
    
for xk in range(xn):
    rSNR3 = rSNR3_range[xk]
    p_add_3 = xor_func(rSNR3)
    for yk in range(yn):
        rSNRdu = rSNRdu_range[yk]
        xor_opt = xor_analysis_pruned(N, tSNR, rSNRdu, rSNR3, downfunc(rSNRdu), upfunc(rSNRdu), p_add_3)
        testleah[xk, yk] = 1 - xor_opt
#         Z[np.where(rSNR3_range==rSNR3)[0][0], np.where(rSNRdu_range==rSNRdu)[0][0]] = 1 - xor_opt

CPU times: user 13.8 s, sys: 89.1 ms, total: 13.9 s
Wall time: 15.4 s


In [ ]:
%%time
%run ../optimize_pkg_2.py
N = 8
tSNR_range = np.arange(16.6, 16.7, 0.1)
rSNR3_range = np.arange(1.9, 2, 0.1)
rSNRdu_guess = 0.6
rSNRdu_range = np.arange(rSNRdu_guess-0.5, rSNRdu_guess+0.5+0.1, 0.1)

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, True)

print result

In [90]:
xn, yn = result.shape
fig = figure()

for xk in range(xn):
    plot(rSNRdu_range, result[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(result[xk])]

xlabel('rSNRdu', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

[[  2.83184431e-09   1.44483270e-09   9.69793579e-10   7.94438404e-10
    7.37519157e-10   7.35799643e-10   7.62190977e-10   8.03411004e-10
    8.53465409e-10   9.08583986e-10   9.67132818e-10]
 [  3.04189696e-09   1.54954494e-09   1.03661679e-09   8.46769099e-10
    7.86143595e-10   7.85068344e-10   8.14710521e-10   8.61253735e-10
    9.17542597e-10   9.79864301e-10   1.04633524e-09]]
0.6
0.6


In [ ]:
%%time
%run ../optimize_pkg_2.py
N = 8
tSNR_range = np.arange(16.4, 16.6, 0.1)
rSNR3_range = np.arange(1.8, 1.92, 0.01)
rSNRdu_range = [0.54]

result = optimize_3_graphical(N, rSNRdu_range, rSNR3_range, tSNR_range, filepath_down, filepath_up, protocolbit, False)

print result

In [95]:
xn, yn = result.shape
fig = figure()
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),), lw=2.0, label='Protocol')
for xk in range(xn):
    plot(rSNR3_range, result[xk], lw=2.0, label='{0}'.format(tSNR_range[xk]))
    print rSNR3_range[np.argmin(result[xk])]

xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

xn, yn (3, 12) size of matrix 36
[[  1.06888942e-09   1.05321152e-09   1.04118292e-09   1.03225806e-09
    1.02602993e-09   1.02214504e-09   1.02029718e-09   1.02022124e-09
    1.02168740e-09   1.02441600e-09   1.02832143e-09   1.03332032e-09]
 [  9.20840515e-10   9.04259778e-10   8.91160368e-10   8.81083428e-10
    8.73479289e-10   8.68298988e-10   8.65097438e-10   8.63614957e-10
    8.63626837e-10   8.64938343e-10   8.67382055e-10   8.70733707e-10]
 [  7.96091415e-10   7.78762055e-10   7.64825980e-10   7.53834994e-10
    7.45398410e-10   7.39178718e-10   7.34882599e-10   7.32256367e-10
    7.30927541e-10   7.31005478e-10   7.32178318e-10   7.34304284e-10]]
1.87
1.87
1.88


<string>:182: RuntimeWarning: divide by zero encountered in log10


In [48]:
print rSNRdu_range
print testleah

# print rSNRdu_range[np.argmin(testleah[1])]
# print rSNRdu_range[np.argmin(testleah[2])]

# label represents rSNR3
fig = figure()
for xk in range(xn):
    plot(rSNRdu_range, testleah[xk], lw=2.0, label='{0}'.format(rSNR3_range[xk]))
    print rSNRdu_range[np.argmin(testleah[xk])]
# plot(rSNRdu_range, testleah[1], lw=2.0, label='1.2')
# plot(rSNRdu_range, testleah[2], lw=2.0, label='1.3')
# plot(rSNRdu_range, testleah[3], lw=2.0, label='1.6')
xlabel('rSNRdu', fontsize=20)
ylabel('P(fail', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

[ 0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1]
[[  2.77118550e-09   1.46758428e-09   1.02038911e-09   8.54754378e-10
    8.01092859e-10   7.99619038e-10   8.24637358e-10   8.63428329e-10
    9.10448161e-10   9.61420055e-10   1.01524023e-09]
 [  2.83184431e-09   1.44483270e-09   9.69793579e-10   7.94438404e-10
    7.37519157e-10   7.35799643e-10   7.62190977e-10   8.03411004e-10
    8.53465409e-10   9.08583986e-10   9.67132818e-10]]
0.6
0.6


In [33]:
print rSNR3_range
print testleah

# print rSNRdu_range[np.argmin(testleah[0])]
# print rSNRdu_range[np.argmin(testleah[1])]
# print rSNRdu_range[np.argmin(testleah[2])]

# label represents rSNR3
fig = figure()
plot(rSNR3_range, testleah[:,0], lw=2.0, label='0.3')
# plot(rSNR3_range, testleah[1], lw=2.0, label='1.2')
# plot(rSNR3_range, testleah[2], lw=2.0, label='1.3')
# plot(rSNRdu_range, testleah[3], lw=2.0, label='1.6')
xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9]
[[  3.77032372e-09]
 [  1.26191357e-09]
 [  7.92230392e-10]
 [  7.53072937e-10]
 [  8.00473465e-10]
 [  8.67715122e-10]
 [  9.42856238e-10]
 [  1.02362130e-09]
 [  1.11105836e-09]
 [  1.20474941e-09]]


In [71]:
%%time
# set tSNR, see shape of rSNRdu vs rSNR3
N = 8
tSNR_range = np.arange(16.4, 16.6, 0.1)
rSNR3_range = np.arange(1.8, 1.92, 0.01)
# rSNRdu_guess = 0.5
# rSNRdu_range = np.arange(rSNRdu_guess-0.5, rSNRdu_guess+0.5+0.1, 0.1)
rSNRdu = 0.54

downbit = upbit = xorbit = 4*10**4/3
downTable = load_table(filepath_down+str(N)+extension)
downfunc = interp1d(downTable[0], downTable[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))
upTable = load_table(filepath_up+str(N)+extension)
upfunc = interp1d(upTable[0], upTable[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))

xor_table = load_table(filepath_up+str(N)+extension)
xor_func = interp1d(xor_table[0], xor_table[1], kind='linear', bounds_error=False, fill_value=(1.0, 0.0))

p_a1, p_a2 = downfunc(rSNRdu), upfunc(rSNRdu)

xn, yn = len(tSNR_range), len(rSNR3_range)

testleah = zeros((xn, yn))
    
for xk in range(xn):
    tSNR = tSNR_range[xk]
    for yk in range(yn):
        rSNR3 = rSNR3_range[yk]
        p_add_3 = xor_func(rSNR3)
        xor_opt = xor_analysis_pruned(N, tSNR, rSNRdu, rSNR3, p_a1, p_a2, p_add_3)
        testleah[xk, yk] = 1 - xor_opt
#         Z[np.where(rSNR3_range==rSNR3)[0][0], np.where(rSNRdu_range==rSNRdu)[0][0]] = 1 - xor_opt

CPU times: user 20.3 s, sys: 128 ms, total: 20.5 s
Wall time: 21.2 s


In [72]:
# 1.03503972e-09, 1.03282849e-09, 1.03103415e-09, 1.02982589e-09, 1.02891895e-09, 1.02832143e-09
# print rSNR3_range
print testleah

# print rSNRdu_range[np.argmin(testleah[0])]
# print rSNRdu_range[np.argmin(testleah[1])]
# print rSNRdu_range[np.argmin(testleah[2])]

# label represents rSNR3
fig = figure()
for idx in range(xn):
    plot(rSNR3_range, testleah[idx], lw=2.0, label='{0}'.format(tSNR_range[idx]))
    print rSNR3_range[np.argmin(testleah[idx])]
# plot(rSNR3_range, testleah[1], lw=2.0, label='1.2')
# plot(rSNR3_range, testleah[2], lw=2.0, label='1.3')
# plot(rSNRdu_range, testleah[3], lw=2.0, label='1.6')
plot(rSNR3_range, 10**(-9)*ones(len(rSNR3_range),))
xlabel('rSNR3', fontsize=20)
ylabel('P(fail)', fontsize=20)
title('N={0}'.format(N), fontsize=20)
legend(loc=0)
mpld3.display(fig)

[[  1.06888942e-09   1.05321152e-09   1.04118292e-09   1.03225806e-09
    1.02602993e-09   1.02214504e-09   1.02029718e-09   1.02022124e-09
    1.02168740e-09   1.02441600e-09   1.02832143e-09   1.03332032e-09]
 [  9.20840515e-10   9.04259778e-10   8.91160368e-10   8.81083428e-10
    8.73479289e-10   8.68298988e-10   8.65097438e-10   8.63614957e-10
    8.63626837e-10   8.64938343e-10   8.67382055e-10   8.70733707e-10]
 [  7.96091415e-10   7.78762055e-10   7.64825980e-10   7.53834994e-10
    7.45398410e-10   7.39178718e-10   7.34882599e-10   7.32256367e-10
    7.30927541e-10   7.31005478e-10   7.32178318e-10   7.34304284e-10]]
1.87
1.87
1.88


In [49]:
%%time
%run ../optimize_3_dct.py
N = 8
d_rSNR = 0.1
d_tSNR = 0.1
tx_SNR_range = np.arange(tSNR_start[N], 50, d_tSNR)
optimize_3_data[N-start_node] = optimize_3(N, rSNRdu_start[N], rSNR3_start[N], tx_SNR_range, filepath_down, filepath_up, protocolbit, d_rSNR)
print optimize_3_data[N-start_node]

7.35799643437e-10
[  1.66000000e+01   6.00000000e-01   1.90000000e+00   8.77638952e-22
   5.37001034e-04   9.01178423e-11]
CPU times: user 668 ms, sys: 28.8 ms, total: 697 ms
Wall time: 878 ms
